### ISSUE TITLE
[FEATURE] Filter by event start time

### ISSUE THREAD

**Issue by tbwfdu** [marksie1988/atomic-calendar-revive#104]
I work for a Global Company and they add lots of recurring meetings outside my timezone to my calendar.

It would be good to be able to filter these out from my calendar view by setting a whitelist of start and finish times to show in the UI.

I've tried using the text whitelist for things like '1:00 AM, 12:00 AM' but that doesn't not work as I think it looks at subject and body.

**Comment by marksie1988** [comment]
Fixed in #237
