### ISSUE TITLE
[BUG] Repeated Calendar Entries not showing on Month View

### ISSUE THREAD

**Issue by honkerst** [marksie1988/atomic-calendar-revive#106]
I'm seeing the same behaviour as this [closed issue](https://github.com/marksie1988/atomic-calendar-revive/issues/90). 

Describe the bug
Events that repeat daily only appear on the first day of the calendar. 

To Reproduce
Add some events that repeat daily. 

Expected behavior
I expect to see the events listed on every day of the month. 

In the screenshot below are both calendars are showing the same google calendar. The calendar only contains 5 events which repeat every day. However there is only an icon on the first day of the month. Clicking the first day (27 April) shows the day's events. Clicking any of the other days does nothing. 

Screenshots
<img width="423" alt="Screenshot 2020-05-18 at 03 04 52" src="https://user-images.githubusercontent.com/43205559/82167703-87512a00-98b4-11ea-83c4-36f4b07feea2.png">

Setup Information (please complete the following information):

Plugin Version 
1.4.2

Browser & Version 
Chrome 81.0.4044.138
Opera 68.0.3618.104

Additional context
This also affects the List view, where you only see the repeating events for 1 day, no matter what maxDaysToShow or maxEventCount are set to.

**Comment by marksie1988** [comment]
@honkerst I think I am now seeing this and just want to check do you have multiple calendars?

Would it be possible to post a copy of your card config as this helps me set my tests up the same to make sure I see the same issues.

**Comment by honkerst** [comment]
No problem, thanks for looking at it. 

I am only using one calendar in both of these calendars. 

My config looks like this: 

` - type: horizontal-stack
    cards:
      - type: "custom:atomic-calendar-revive"
        name: Calendar
        enableModeChange: true
        defaultMode: 2
        dateFormat: L
        maxDaysToShow: 30
        sortByStartTime: true
        showDescription: true
        showNoEventsForToday: true
        entities:
          - entity: calendar.automator
            type: icon3
  - type: horizontal-stack
    cards:
      - type: "custom:atomic-calendar-revive"
        name: "Scheduled events"
        entities:
          - entity: calendar.automator
        fullDayEventText: 'All day'
        untilText: 'Until'
        enableModeChange: true
        showColors: true
        maxDaysToShow: 30
        maxEventCount: 0
        showLocation: true
        showMonth: true
        showWeekDay: true
        disableEventLink: true
        disableLocationLink: true
        showCurrentEventLine: false
        dateColor: '#DDDDDD'
        dateSize: 90
        timeColor: '#cccccc'
        timeSize: 80
        titleColor: '#ffffff'
        titleSize: 100
        locationIconColor: 'rgb(230, 124, 115)'
        locationLinkColor: '#BBBBBB'
        locationTextSize: 90
        dimFinishedEvents: true
        finishedEventOpacity: 0.3
        finishedEventFilter: 'grayscale(100%)'
        dayWrapperLineColor: '#999999'
        eventBarColor: '#aaaaaa'
        showProgressBar: true
        progressBarColor: '#aaaaaa'`

**Comment by marksie1988** [comment]
Thanks, next time I'm working on the card I will take a look at this and try figure out what's happening. 

I'm currently working on the next feature release so will try get this fixed as part of that. If not I'll prioritise it for after.

**Comment by marksie1988** [comment]
@honkerst ok im not sure this is a bug as my test calendar with the above config appears to work at first glance. 

have you followed the setup [here](https://marksie1988.github.io/atomic-calendar-revive/quickstart.html) specifically [showing more than 5 events](https://marksie1988.github.io/atomic-calendar-revive/quickstart.html#show-more-than-5-events)

![image](https://user-images.githubusercontent.com/159166/82247503-6503ee80-993e-11ea-845a-59d2ff649bab.png)
You can see here all the daily scheduled events from  the 18th onwards.

**Comment by honkerst** [comment]
No, dammit, I didn't see that bit about showing more than 5 events! Thanks a bunch! That completely solves my problem.

One last question, on some days I have more than 10 events. To get icons on every day of the monthly calendar I'd have to set max_results to 400 or 500. Is that feasible or is such a large number going to cause problems?

**Comment by honkerst** [comment]
I've tried out 500, and it seems to be fine. Loads quickly, and moving from month to month loads all events for all days. 

I did notice that if I am in list mode and choose maxEventCount: 20 it correctly displays 20 events, but if I enableModeChange is set to true and I click the header to change modes there are 0 icons on the calendar, not even on the first two days.

**Comment by marksie1988** [comment]
Unfortunately i have never set it to something so high so wouldn't know. 

As that is part of the HA integration for Google Calendar it may be worth asking on the HA forums :)

**Comment by marksie1988** [comment]
> I did notice that if I am in list mode and choose maxEventCount: 20 it correctly displays 20 events, but if I enableModeChange is set to true and I click the header to change modes there are 0 icons on the calendar, not even on the first two days.

I will take a look at this :)

**Comment by honkerst** [comment]
I take it all back. I didn't have 'type: icon3' on that calendar. It's working properly (in fact it's even better than expected, changing modes displays all 500 events, and list mode only shows the next 20, this is even better than expected).

You can close this ticket, thanks for all your help :-)

**Comment by marksie1988** [comment]
Glad all is working for you :)
