### ISSUE TITLE
[BUG] Custom color doesn't work across all themes

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#133]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  * Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  * Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Custom text color is making it not readable on my theme

**Expected behavior**

Custom colors should not be used by default. There are CSS variables which are available for all the cards:
![image](https://user-images.githubusercontent.com/8268674/83047639-8a7cb080-a040-11ea-9412-fa2555f03127.png)

My suggestion is to use the primary one

**Actual behavior:**

**Screenshots**

![image](https://user-images.githubusercontent.com/8268674/83047361-2bb73700-a040-11ea-9140-9a6a591f79ad.png)

### Versions
v1.6.0
* HomeAssistant Version:
* Plugin Version:

**Comment by marksie1988** [comment]
Hey,

Thanks for this, I will take a look at it as soon as I can.
