### ISSUE TITLE
[FEATURE] Disable progress bar for all-day events

### ISSUE THREAD

**Issue by Rikkie80** [marksie1988/atomic-calendar-revive#145]
## Summary

Disable progress bar for all day event only

## Motivation

To me it doesn't make sense to show a progress bar in an all-day event. In fact the progress of the day is measured instead of the event itself

## Describe alternatives you've considered

Just accept as it is...;)

## Additional context

For shorter meetings/appointments it makes sense to have a progress bar so I would still see the progress bar for such events.

**Comment by marksie1988** [comment]
Feature has now been added :)

**Comment by Rikkie80** [comment]
Tried to add showFullDayProgress : true and false but without success... Is this the correct implementation?

**Comment by marksie1988** [comment]
Hey,

If you have updated to the latest version make sure it shows v1.7.0 in the develoent console in your browser, sometimes the script is cached by the browser and takes a while to refresh.

**Comment by Rikkie80** [comment]
Sorry, my fault. Deinstalled atomic calendar after installing atomic calendar revive... Reinstalled revive 1.7.0 and now it works. Thanks for the very quick implementation!

**Comment by marksie1988** [comment]
No problem at all, I had just fixed a bug so thought I may as well do it as it was a quick fix

**Comment by formadelfo** [comment]
nice, i also didn't like the progress bar. Will update now and turn it off. Great work!
