### ISSUE TITLE
titleSize config not responding

### ISSUE THREAD

**Issue by krkn0** [marksie1988/atomic-calendar-revive#156]
# Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

titleSize not working

### Steps to Reproduce

1. Edit calendar card
2. Show code editor
3. Insert: titleSize: 130 (instead of default 100)

**Expected behavior**

titleSize changes to 130

**Actual behavior:**

titleSize remains 100

**Screenshots**

<img width="982" alt="screenshot" src="https://user-images.githubusercontent.com/26967668/83306872-abd9ca00-a203-11ea-816d-0011c3cd7aed.png">

**Card Configuration**
dateSize: 130
enableModeChange: true
entities:
  - entity: calendar.xxxxx
  - entity: calendar.xxxxx
  - entity: calendar.xxxxx
  - entity: calendar.xxxxx
  - entity: calendar.xxxxx
hoursFormat: 24h
name: Calendar
showDate: false
showDescription: false
showWeekDay: true
sortByStartTime: true
timeSize: 130
titleSize: 130
type: 'custom:atomic-calendar-revive'

### Versions

- HomeAssistant Version: Home Assistant 0.110.3
- Plugin Version: v1.8.5

**Comment by marksie1988** [comment]
This option should be `eventTitleSize` which was recently changed.
