### ISSUE TITLE
the calendar can't be loaded from home assistant component

### ISSUE THREAD

**Issue by aaamoeder** [marksie1988/atomic-calendar-revive#172]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

After migrating to a new install, the error "the calendar can't be loaded from home assistant component" shows.
The configuration is the exact same as in my previous install where it is still functioning.
Installed latest version from HACS, also tried older versions without success.
Google calendar sensors are working as they should.
Tried removing the google token and re-authenticating with no improvement.
nothing in the logs.

### Steps to Reproduce

1. migrate
2. install from HACS
3. copy over config
4. restart HA
5. error..

**Expected behavior**

a functioning card

**Actual behavior:**

a non functioning card

**Card Configuration**

```
              - type: 'custom:atomic-calendar-revive'
                entities:
                  - entity: calendar.gimme_steve_jaspers
                  - entity: calendar.aliesbeyersgmailcom
                  - entity: calendar.kids_algemeen
                  - entity: calendar.moeke_voss
                  - entity: calendar.opleidingen
                  - entity: calendar.ruben
                  - entity: calendar.aaron
                  - entity: calendar.steve_werken
                  - entity: calendar.stevejaspers83gmailcom
                  - entity: calendar.verjaardagen
                  - entity: calendar.worldwide_space_launches
                    whitelist: 'spacex'
                  - entity: calendar.feestdagen_in_belgie
                  - entity: calendar.family
                  - entity: calendar.belangrijk
                  - entity: calendar.anderlecht
                dateColor: "#f5b400"
                dateSize: 110
                dayWrapperLineColor: "#cfd2d9"
                showWeekDay: true
                dimFinishedEvents: true
                finishedEventFilter: grayscale(100%)
                finishedEventOpacity: 0.4
                fullDayEventText: Hele dag
                locationIconColor: "#f5b400"
                locationLinkColor: "#f5b400"
                locationTextSize: 100
                maxDaysToShow: 31
                progressBarColor: "#f5b400"
                showColors: true
                showCurrentEventLine: false
                showLocation: true
                showMonth: false
                showNoEventsForToday: true
                showProgressBar: true
                disableEventLink: true
                disableLocationLink: true
                timeColor: "#f5b400"
                timeSize: 100
                name: ""
                titleColor: "#cfd2d9"
                titleSize: 110
                untilText: Until
                gridrow: 3 / 5
                gridcol: 1 / 2
                style: |
                  ha-card {
                    height: 100% !important;
                    padding: 0px 0px 0px 0px !important;
                    overflow: hidden !important;
                    border-top: 1px solid #cfd2d9;
                  }
                  hr.progress {
                    border-width: 2px 0 0 0 !important;
                  }
                  .cal-nameContainer {
                    display: none !important;
                  }
```

### Versions

- HomeAssistant Version: 0.111
- Plugin Version: 1.8.7

**Comment by marksie1988** [comment]
Hey There, 

Could you run through the following: 

- Confirm that you added `local/community/atomic-calendar-revive/atomic-calendar-revive.js` to the dashboard resources
- Confirm that under developer tools sources you see `local/community/atomic-calendar-revive/atomic-calendar-revive.js`
- Confirm that under developer tools console you see `atomic-calendar-revive version: 1.8.7`
- Confirm that you have removed any old versions of atomic calendar as these can conflict
  - delete any `atomic_calendar` folders or `atomic_calendar_revive`

**Comment by aaamoeder** [comment]
> Hey There,
> 
> FYI I have also tested on my test platform with 0.111 and 1.8.7 without any issues using your configuration.
> 
> Could you run through the following:
> 
> * Confirm that you added `local/community/atomic-calendar-revive/atomic-calendar-revive.js` to the dashboard resources
> * Confirm that under developer tools sources you see `local/community/atomic-calendar-revive/atomic-calendar-revive.js`
> * Confirm that under developer tools console you see `atomic-calendar-revive version: 1.8.7`
> * Confirm that you have removed any old versions of atomic calendar as these can conflict
>   
>   * delete any `atomic_calendar` folders or `atomic_calendar_revive`

* I have "/hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js" in the resources (otherwise the card wouldn't be loading at all would it ?)
* When inspecting the page I see "/hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js" in sources.
* in developer tools - console I do see "atomic-calendar-revive version: 1.8.7"
* There have never been any other versions installed since this is a clean HA install.

thanks for your quick response btw !

**Comment by aaamoeder** [comment]
nevermind.. I already found it..
It seems that for some reason the repopulation of the "google_calendars.yaml" file generated different entity ids as before now replacing "." with "_" where before the "." was simply removed resulting in faulty entity id's in my lovelace yaml...

**Comment by marksie1988** [comment]
Glad you sorted it.
