### ISSUE TITLE
Event list does not show correct date

### ISSUE THREAD

**Issue by haegar33** [marksie1988/atomic-calendar-revive#174]
### Prerequisites

- [ x] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Event List show only current date at first event. Next events in following line do not show any date info.

**Expected behavior**

Expecting the date of the event next to the description

**Actual behavior:**

[**Screenshots**
[https://abload.de/img/screenshot2020-06-14agbjmx.jpg](url)

**Card Configuration**

type: 'custom:atomic-calendar-revive'
entities: calendar.privates
name: Termine
maxDaysToShow: 14

`### Versions

- HomeAssistant Version: all latest
- Plugin Version:

**Comment by haegar33** [comment]
[
![Screen Shot 2020-06-14 at 11 20 45](https://user-images.githubusercontent.com/22793462/84589971-ce3e2b00-ae32-11ea-97a2-bd3f5dac6ede.jpg)
](url)

**Comment by marksie1988** [comment]
So is the issue that these events shouldnt be showing under the 14th and should only be under the 13th? 

If you have multiple events on one day, it is normal that the date will only appear next to the first event for that day,

**Comment by haegar33** [comment]
Sorry, I think I was not clear on the description. I am using a caldav calendar entity (which works fine in HA). Events are extracted but all have the date set to the current date. There is an error in the date parsing function for a calddav event (maybe different from Google calendars?)
![calendar](https://user-images.githubusercontent.com/22793462/87222838-ca40f280-c377-11ea-896a-0708bbcc26d0.jpg)

**Comment by idittansikte** [comment]
I have the same issue using caldav. 

This Caldav item:

```
message: Bar
all_day: true
start_time: '2020-07-06 00:00:00'
end_time: '2020-08-03 00:00:00'
location: null
description: null
offset_reached: false
friendly_name: foo
```

Shows as  "All day, until July 19" and today is July 20. Another item that are from  July 23 -  July 25 is shown the same even though its a day in the future.

**Comment by marksie1988** [comment]
Thanks for the feedback, I will see if I can setup a caldav and hopefully will have some time to look at this as part of v2 release and see if there is a simple fix that could be implemented. 

As this is designed for use with Google calendar I can't guarantee I will get it working but will try, have some good ideas around it to also include some other functionality.

**Comment by marksie1988** [comment]
I have now setup a NextCloud test server to have a look at this, this is now the only outstanding issue with v2.0

**Comment by haegar33** [comment]
I just installed the very last version and the error remains, actually looks even more bizarre, every event is "all day", dates in the past etc. Apparently the script cannot handle date formats provided by caldav servers. In the HA mainpage my calendar dates are all correct thus no error on the caldav binding.

Screenshot below: German "vor 14 Stunden" means "14h ago"

![Screen Shot 2020-08-17 at 14 06 21](https://user-images.githubusercontent.com/22793462/90394583-34de0000-e093-11ea-8a62-a17ec4db314b.jpg)

**Comment by marksie1988** [comment]
Unfortunately I haven't had time to look at this properly yet. Ive been really busy with work. 

I will look as soon as I get some time hopefully over the next week or two.

**Comment by marksie1988** [comment]
I can see that when an event uses caldav that the following is populated: 

```
eventClass:
description: null
end: "2020-08-19T11:00:00+01:00"
location: null
start: "2020-08-19T10:00:00+01:00"
summary: "test NC"
uid: "dfb0d768-2be0-463c-bf73-bd958bc549ff"
```
This event happens between 10am and 11am on the 19th but actually when processed by Moment the dates change: 

```
_endTime: v
_d: Mon Aug 17 2020 23:59:59 GMT+0100 (British Summer Time) {}
_isAMomentObject: true
_isUTC: false
_isValid: true
_locale: E {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", _dayOfMonthOrdinalParse: /\d{1,2}(st|nd|rd|th)/, ordinal: ƒ, …}
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, charsLeftOver: 0, …}
__proto__: Object
_startTime: v
_d: Tue Aug 18 2020 00:00:00 GMT+0100 (British Summer Time) {}
_isAMomentObject: true
_isUTC: false
_isValid: true
_locale: E {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", _dayOfMonthOrdinalParse: /\d{1,2}(st|nd|rd|th)/, ordinal: ƒ, …}
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, charsLeftOver: 0, …}
__proto__: Object
```
So between the card receiving the data and then processing it the date information is lost.

**Comment by marksie1988** [comment]
Ok i have now found the cause of this issue. 

An event from Google will come in this format: 
```
end:
    dateTime: "2020-08-20T11:00:00+01:00"
    timeZone: "Europe/London"
```
where as CalDav is like this:
```
end: "2020-08-19T11:00:00+01:00"
```
Google are adding an extra level to events that arent full day, this means that when there is no "dateTime" the card will assume that its an all day event, an all day event in Google is `end.date` however from caldav as you can see all events just show as `end`

I will add an additional check for this which should mitigate against this.

**Comment by haegar33** [comment]
I can confirm that with your latest alpha branch 2.2.3 the caldav event are now properly displayed in the event list.
Thanks for your effort!

**Comment by idittansikte** [comment]
Awesome! Will try it out asap!
Thank you!

**Comment by marksie1988** [comment]
I think there are still some issues which is why I've not pushed it to the master yet. 

Unfortunately I'm really busy preparing for an exam at the moment but hopefully I'll be back at it mid next week 🙂
