### ISSUE TITLE
Icon filter doesn't work

### ISSUE THREAD

**Issue by 213garcia** [marksie1988/atomic-calendar-revive#183]
I put three icons under one entity (one calendar) and all three icons have filters (exact words which trigger exact icon).
When there is any event on some day there are three icons on this day but event name has "filter word" from only one icon filter.

**Comment by marksie1988** [comment]
Please make sure to fill out the template for creating an issue.

**Comment by 213garcia** [comment]
HA 0.111.4
ADD-ON 1.9.0

**Comment by marksie1988** [comment]
closing, please log correctly through the bug template, i cant troubleshoot this with such little information about your setup etc. 

https://github.com/marksie1988/atomic-calendar-revive/issues/new/choose
