### ISSUE TITLE
Icon filter doesn't work

### ISSUE THREAD

**Issue by 213garcia** [marksie1988/atomic-calendar-revive#195]
### Prerequisites

- [X ] Put an X between the brackets on this line if you have done all of the following:
  -  Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Icon filter doesn't work. Even I have entry in calendar where its name contains only one word from 3 filters there are three icons in this day.

### Steps to Reproduce

1. create calendar entities
2. import calendars into card which is placed in lovelace
3. create filters in calendar card
4. create event in calendar which name contain one word from one filter

**Expected behavior**

only one icon should be visible if words from name of the event are in only one filter

**Actual behavior:**

all three icons are visible

**Screenshots**

https://paste.pics/1bf2491c1d14f1ba3995c634bd84dd27

**Card Configuration**

          - CalEventIcon1Filter: 'urodziny,Urodziny,URODZINY,imieniny,Imieniny,IMIENINY'
            CalEventIcon3Filter: 'licznik,Licznik,LICZNIK'
            calEventIcon1: 'mdi:gift-outline'
            calEventIcon2: 'mdi:calendar-today'
            calEventIcon3: 'mdi:water-pump'
            defaultMode: 2
            enableModeChange: false
            entities:
              - entity: calendar.family
                type: 'icon1,icon2,icon3'
              - entity: calendar.swieta_w_polsce
                type: holiday
            finishedEventFilter: grayscale(100%)
            finishedEventOpacity: 0.6
            fullDayEventText: Cały dzień
            locationTextSize: 90
            maxDaysToShow: 60
            showColors: false
            showCurrentEventLine: false
            showLocation: true
            showMonth: true
            showProgressBar: true
            timeSize: 90
            title: null
            titleSize: 100
            type: 'custom:atomic-calendar-revive'
            untilText: Until
          - CalEventIcon1Filter: 'urodziny,Urodziny,URODZINY,imieniny,Imieniny,IMIENINY'
            CalEventIcon3Filter: 'licznik,Licznik,LICZNIK'
            calEventIcon1: 'mdi:gift-outline'
            calEventIcon2: 'mdi:calendar-today'
            calEventIcon3: 'mdi:water-pump'
            dateSize: 90
            defaultMode: 1
            descColor: grey
            enableModeChange: false
            entities:
              - entity: calendar.family
                type: 'icon1,icon2'
              - entity: calendar.swieta_w_polsce
                type: holiday
            finishedEventFilter: grayscale(100%)
            finishedEventOpacity: 0.6
            fullDayEventText: Cały dzień
            locationIconColor: 'rgb(255, 0, 0)'
            locationLinkColor: grey
            locationTextSize: 90
            maxDaysToShow: 60
            showColors: false
            showCurrentEventLine: false
            showDescription: true
            showLocation: true
            showMonth: true
            showProgressBar: true
            timeColor: grey
            timeSize: 90
            title: Wydarzenia
            titleColor: 'rgb(0, 204, 255)'
            titleSize: 100
            type: 'custom:atomic-calendar-revive'
            untilText: Until

### Versions

- HomeAssistant Version: 0.111.4
- Plugin Version: 1.9.0

### Additional Information

Calendar event is called "Licznik wody".
This is only one event on 28.06 but we can see three icons.
There should be water pump icon only because of "Licznik" in "Licznik wody" event.
There are two events on 25.06: "urodziny test" and "webinar".
So there should be only two icons: gift (because of "urodziny" in "urodziny test" event) and calendar event (for "webinar")

**Comment by marksie1988** [comment]
you have only filter for icon1 and icon3, but you have icon1,icon2,icon3 under the entity, this means that icon2 will show if there is an event on that day as it has no filter.

**Comment by 213garcia** [comment]
You are rights but as you can see on 28th there are 3 icons but there should be only 1 icon3 because the name od event is on filter3.
On 25th I have 2 events but 3 icons. 
There should be icon1 and icon3 only.
Please check screenshot.

**Comment by marksie1988** [comment]
Fixed in #237

**Comment by 213garcia** [comment]
Why do I have 3 icons on event "Licznik wody" which should have only 2 (icon2 and icon3)?

**Comment by 213garcia** [comment]
No matters what the name od event is I have always 3 icons. No matters od the name od under filter1 or filter3 or no filter.

**Comment by marksie1988** [comment]
Have you upgraded to version 2 icons have changed in this version and that resolves the issue you are seeing.

**Comment by 213garcia** [comment]
Not yet. HACS hasn't shown new version.

Pozdrawiam/Kind regards,
Marcin Zjawiński

pt., 31 lip 2020, 18:42 użytkownik Steven Marks <notifications@github.com>
napisał:
