### ISSUE TITLE
Hacs install location

### ISSUE THREAD

**Issue by gpend** [marksie1988/atomic-calendar-revive#207]
the hacs install puts the file in /config/www/community/atomic-calendar-revive/atomic-calendar-revive.js but the lovelace resource page shows it as /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js

I am a newbie so I may be missing something.

**Comment by marksie1988** [comment]
Hey @gpend, 

No worries, i had the same issue when i started, `/hacsfiles/` maps to `/config/www/community`

**Comment by marksie1988** [comment]
closing this as there has been no further update.
