### ISSUE TITLE
The calendar can't be loaded from Home Assistant component

### ISSUE THREAD

**Issue by IrealiTY** [marksie1988/atomic-calendar-revive#233]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

The card displays the error `The calendar can't be loaded from Home Assistant component` instead of showing any calendar entries.

Important to note:

- I'm *not* the owner of the calendar but was added to it via a family member, I do have full read and write access though.
- HomeAssistant sidebar calendar displays it properly 

### Steps to Reproduce

1.  Make a new card
2.  Add YAML to card

**Expected behavior**

Calendar Events visible

**Actual behavior:**

"The calendar can't be loaded from Home Assistant component"

**Screenshots**

![image](https://user-images.githubusercontent.com/1223686/88947600-0ab5d100-d291-11ea-9c60-1e06ebb716f6.png)

**Card Configuration**

```yaml
entities:
  - entitiy: calendar.lucile_aleks_shared_calendar
name: Our Calendar
type: 'custom:atomic-calendar-revive'
```

### Versions

- HomeAssistant Version: 0.113.2
- Plugin Version: v1.9.0

### Additional Information

Like this issue https://github.com/marksie1988/atomic-calendar-revive/issues/172 I also tried deleting my `google_calendars.yaml` to have correct IDs and restart HA but this didn't seem to fix the issue.

**Comment by marksie1988** [comment]
Hi @IrealiTY do you see your google calendars under the entities? 

Usually this means that the card is loading correctly but that there is a configuration issue somewhere else e.g. google calendars or HA.

**Comment by IrealiTY** [comment]
Thanks for your reply :)
Yes the calendars are visible in the entities list
![image](https://user-images.githubusercontent.com/1223686/89112221-ca587d80-d45f-11ea-80ce-dbaef927996c.png)

**Comment by marksie1988** [comment]
have you restarted HA since using the card? it may be worth giving this a shot. 

Basically the point that this error is displayed is when the card is trying to get a list of events but is unable to get any results.

**Comment by IrealiTY** [comment]
Yeah did restart a few times. Its really weird, if I check in the states of the calendar in the dev tools it even shows up properly.
![image](https://user-images.githubusercontent.com/1223686/89404197-de2f0880-d719-11ea-8fbc-19c35df98692.png)

I'll try adding a different calendar later and have a go with that, will report back.

**Comment by IrealiTY** [comment]
Reporting back, same issue :(

I did notice though that Chrome DevTools throw an error about calendars, not sure if related:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)            atomic-calendar-revive.js:433 
```

**Comment by marksie1988** [comment]
Ok in that case it looks like the file is either missing, or what was entered into the Lovelace dashboard resources is incorrect. 

Could you post what you put in the resources section?
Also could you double check the file exists on your HA server? (It is usually www/community/atomic-calendar-revive/atomic-calendar-revive.js)

**Comment by marksie1988** [comment]
closing due to no response.
