### ISSUE TITLE
Change the way days are colored and highlighted

### ISSUE THREAD

**Issue by tomasrudh** [marksie1988/atomic-calendar-revive#239]
## Summary

Suggestion to make coloring and highlighting of days clearer.

## Motivation

As it is now can a certain day only show one color, but it might be needed to show several statuses like weekend, selected day and current day.

## Describe alternatives you've considered

I suggest todays day is highlighted by making the frame around the day stand out, instead of a different background color. As an alternative could the text color for todays day be set to the same as an active icon, paper-item-icon-active-color.

**Comment by marksie1988** [comment]
This isnt something that im going to implement, however what I have done is changed the code in v2.1.0 to use a class instead of style. 
By doing this you will be able to style the card differently using something like the [lovelace card mod](https://github.com/thomasloven/lovelace-card-mod)
