### ISSUE TITLE
Calendar mode description

### ISSUE THREAD

**Issue by malinduta** [marksie1988/atomic-calendar-revive#240]
Hello!
Is there a way to show event description on calendar mode?

**Comment by marksie1988** [comment]
@malinduta there isn't currently a way to do this, calendar modern is meant to be a more minimalist view.

**Comment by malinduta** [comment]
Can it be added on future releases? It would be great.

**Comment by brianhanifin** [comment]
I just got my iCloud CalDav calendars into Home Assistant. I saw you just got CalDav working, so I guess I had really good timing! :)

I love the Event mode. My wife is very happy this new view on our Kitchen tablet!

But I have been trying to figure out how to get the full Home Assistant Calendar display into my Tablet view. If you could give us an embedded alternative I would really appreciate it.
