### ISSUE TITLE
Files size

### ISSUE THREAD

**Issue by malinduta** [marksie1988/atomic-calendar-revive#243]
Files size from [latest release](https://github.com/marksie1988/atomic-calendar-revive/releases/latest) zip is different than raw github [revive.js](https://raw.githubusercontent.com/marksie1988/atomic-calendar-revive/master/dist/atomic-calendar-revive.js) and [editor.js](https://raw.githubusercontent.com/marksie1988/atomic-calendar-revive/master/dist/atomic-calendar-revive-editor.js)

Manually installing card (copy paste from raw github) is working as expected. Used [this guide](https://marksie1988.github.io/atomic-calendar-revive/quickstart.html).
Using hacs is not working as expected. It takes the files, but different size. Editor does not show correctly in browser.

**Comment by marksie1988** [comment]
Apologies for this, I have checked and it looks like something happened when the merge was committed from the branch to the master. 

This should now be resolved.
