### ISSUE TITLE
Calendar refresh option

### ISSUE THREAD

**Issue by Kokicha** [marksie1988/atomic-calendar-revive#253]
## Summary

Any chance of adding an option to adjust the refresh frequency?
At present I think the calendar checks for updates every minute, which in my browser (kiosk mode) creates a temporary scroll bar at the time of each refresh.  I only need no more than a 10-minute refresh interval.

Thanks for considering.

**Comment by marksie1988** [comment]
I have added a new option `refreshInterval` that will be available in v2.1.0, this will default to 60 seconds but can be changed via the setting.

**Comment by Kokicha** [comment]
> I have added a new option `refreshInterval` that will be available in v2.1.0, this will default to 60 seconds but can be changed via the setting.

Thanks for doing this so quickly @marksie1988. it’s a nice calendar.  Appreciate your work.
