### ISSUE TITLE
Custom element doesn't exist: atomic-calendar-revive.

### ISSUE THREAD

**Issue by stianbru** [marksie1988/atomic-calendar-revive#256]
Hi. 

I get error "Custom element doesn't exist: atomic-calendar-revive" when trying to use code in lovelace card, what am I doing wrong?

```
type: 'custom:atomic-calendar-revive'
title: "My calendar"
progressBar: true
entities:
  - calendar.private_calendar

```
Kind regards

Stian

**Comment by marksie1988** [comment]
Hi there, 

This usually happens when the card isn't loaded into the interface correctly. 

Please check F12 on the console you should see atomic-calendar-revive with the version number you installed. 

also make sure you added the calendar to the resources section in HA.

**Comment by stianbru** [comment]
Hi again.

I am a noob, forgot to add the calendar to resources in lovelace. When that was done and cache was cleared everything works. Thanks for help @marksie1988 :)
