### ISSUE TITLE
[Feature Request] configurable icons for every event in event mode

### ISSUE THREAD

**Issue by thorschtn** [marksie1988/atomic-calendar-revive#257]
## Summary

Show configurable icons like holiday, birthday, waste in event view

## Motivation

I would like to have configurable icons for every event type not only in the calendar mode, but also in event mode. Since event mode is my standard view for calendars, the view would be significantly upgraded with event icons.

**Comment by marksie1988** [comment]
Do you mean you want the ability to see the icons in the event view as well?

**Comment by thorschtn** [comment]
Correct.
Something like:
![image](https://user-images.githubusercontent.com/16856940/89659456-37d93380-d8d0-11ea-84d8-cbede44b92c7.png)
