### ISSUE TITLE
All day event is shown on wrong day still

### ISSUE THREAD

**Issue by tomasrudh** [marksie1988/atomic-calendar-revive#296]
Not sure if I should reopen 292, you get a new bug report.

The issue is still present in v2.2.3, When I add a full day event that ends yesterday does it still show today.
![GoogleCalendar](https://user-images.githubusercontent.com/24943208/92411170-0e1d6180-f147-11ea-855d-2f01c4b23e76.png)
![LovaelaceCards](https://user-images.githubusercontent.com/24943208/92411172-0e1d6180-f147-11ea-9e9d-b657e4e03e70.png)

**Comment by marksie1988** [comment]
That's interesting I'm not seeing this issue, what time zone are you in? 

I'm wondering if that is why I can't see it on my tests.

**Comment by tomasrudh** [comment]
I am in Stockhom, Sweden, so CEST.

**Comment by marksie1988** [comment]
Thanks I'll do some testing and try get a fix out 😊

**Comment by brianhanifin** [comment]
My Timezone is `America/Los_Angeles` and I'm having this issue as well. The way that the Friday and Saturday columns are colored suggests that the system wants the weeks to begin with Monday. I am running Home Assistant Supervised on Ubuntu Server (inside a VirtualBox VM). Whenever I am given the choice I choose Monday as the starting day of the week, splitting the weekend doesn't work as well for my brain.

![Annotation 2020-09-07 134329](https://user-images.githubusercontent.com/57336/92415978-2756eb80-f110-11ea-98cd-f3aee328bfbe.png)

**Comment by marksie1988** [comment]
Yes I've just done some testing. For some reason it isn't obeying the start day of the week for the days along the top of the calendar, even though the actual dates move to the correct week

**Comment by lancelon** [comment]
Seem to have the same issue, 
![day before](https://user-images.githubusercontent.com/28266789/149759134-650eb093-59d3-4194-b63c-ef5278296a03.png)
@marksie1988 (sorry don't know if you'd see this if I didn't tag you!)
an all day event from day before showing today for some reason
