### ISSUE TITLE
All day event doesn't show full day event text

### ISSUE THREAD

**Issue by thorschtn** [marksie1988/atomic-calendar-revive#297]
With updating to version 2.2.3 the full day event text isn't shown anymore.
It now shows **_12:00 AM - 11:59 PM(in 16 hours)_** instead of the configured full day event text.

**Comment by breti** [comment]
Not solved completely:

![grafik](https://user-images.githubusercontent.com/3628895/92724535-13f38c80-f36b-11ea-9934-d2054fca626e.png)

**Comment by marksie1988** [comment]
@breti  Please check in your browser console that v2.2.6 is being loaded. Make sure that it isn't cached on the old version.  

If this isn't the case please let me know.

**Comment by breti** [comment]
![grafik](https://user-images.githubusercontent.com/3628895/92725886-15be4f80-f36d-11ea-90bc-1a1a9f797d75.png)

![grafik](https://user-images.githubusercontent.com/3628895/92725973-2ff82d80-f36d-11ea-83c3-c3fdb38427be.png)

I've tried Firefox Private Mode and reloaded Lovelace with Ctrl+Shift+R, still the same. Then I've tried Chrome, still the same.

**Comment by marksie1988** [comment]
Ok thanks, I'll do some testing again on that
