### ISSUE TITLE
Support prioritizing events based on start time rather than calendar order when maxEventCount is set

### ISSUE THREAD

**Issue by Johmpa** [marksie1988/atomic-calendar-revive#298]
## Summary

I'd like a configuration option to enable a card with multiple calendars and a maxEventCount and maxDaysToShow set to prioritize which events to include based on start-time rather than the order in which calendars are specified. 

## Motivation

I like to keep my events categorized by context, i.e. one for work, one for private engagements, one for events with friends, one specifying public events etc. As such my configuration for the card contains eight separate calendars. My panel setup also has limited screen real-estate meaning I need to restrict the amount of events shown. 

I order my events based on start time and have set maxEventCount to 8 or 10 depending on other factors. The behavior with a setup such as this is that the card will fetch events from the first calendar specified up to the maxDaysToShow limit. If will only fetch events from the next calendar if the limit set in maxEventCount has not been reached. 

In this scenario I would like an option to make the card fetch events from all calendars and prioritize inclusion based on the start time, otherwise events in calendars lower down in the list may never be shown if the amount of days is high or if the amount of events on any given day varies greatly. 

## Describe alternatives you've considered
Currently I get around this by using a balanced maxEventCount and maxDaysToShow in order to minimize bias to the first calendars but it makes my calendar somewhat inconsistent in terms of it's visual footprint. 

## Additional context
Here is an example from my setup. The calendars listed are 
        - entity: calendar.personlig
        - entity: calendar.vuxna_man_gor_saker_tillsammans
        - entity: calendar.events
        - entity: calendar.work2
          entity: calendar.work
        - entity: calendar.public
        - entity: calendar.warhammer
        - entity: calendar.helgdagar_i_sverige

In this case the maxEventCount is 10 and the maxDaysToShow is 4.  All the events here are from the "Events" and "Work" calendars. 
![image](https://user-images.githubusercontent.com/1575874/92622450-4f3b8000-f2c5-11ea-91f5-2890c3547964.png)

However, if I change maxDaysToShow to 3 if will look like this instead:
![image](https://user-images.githubusercontent.com/1575874/92623303-544cff00-f2c6-11ea-89e1-66984a245b47.png)

Note the "Important Public Event" entry that suddenly showed up. This is due to it being in the "Public" calendar and thus was never fetched since there were two events from the "Events" calendar that occurs on Saturday and thus superceded it in the previous example.

**Comment by marksie1988** [comment]
Yes I see what you mean here, this will take a little thinking. 

Currently each entity is called in turn. I would need to change this to pull each one in turn and then process everything else such as max events etc.  after we have a full list of events.
