### ISSUE TITLE
Type Error when maxEventCount is set

### ISSUE THREAD

**Issue by Johmpa** [marksie1988/atomic-calendar-revive#329]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

When using the maxEventCount the card reports that it can't load the calendar from the component. Further analysis shows that maxEventCount being set causes the issue. Inspection using Chrome DevTools shows the following error from atomic-calendar-revive.js: 

TypeError: Cannot read property 'daysToSort' of undefined
    at atomic-calendar-revive.js:1466
    at Array.reduce (<anonymous>)
    at atomic-calendar-revive.js:1466
    at async HTMLElement.getEvents (atomic-calendar-revive.js:1466)
    at async HTMLElement.updateCard (atomic-calendar-revive.js:1081)

### Steps to Reproduce

See above. 

**Expected behavior**

See above.

**Actual behavior:**

See above.

**Screenshots**

<img width="854" alt="CalendarError" src="https://user-images.githubusercontent.com/1575874/95460766-a5a7e700-0975-11eb-8b21-507b6116fab7.png">

**Card Configuration**

```
disableEventLink: true
disableLocationLink: true
entities:
  - entity: calendar.events
hideFinishedEvents: true
language: sv
maxDaysToShow: 3
maxEventCount: 9
name: Kalender
noEventsForNextDaysText: Ingenting kommande dagar
noEventsForTodayText: Ingenting idag
progressBarColor: '#116466'
showColors: true
showDate: true
showDescription: false
showEventIcon: false
showFullDayProgress: true
showLoader: true
showLocation: true
showMonth: true
showNoEventsForToday: true
showProgressBar: true
showRelativeTime: true
showWeekDay: true
sortByStartTime: true
timeColor: '#d9b08c'
type: 'custom:atomic-calendar-revive'
firstDayOfWeek: 1
```

### Versions

- HomeAssistant Version: 0.116.0
- Plugin Version: v2.5.0

**Comment by marksie1988** [comment]
Thanks for this I will investigate as I haven't seen this in my testing. I will try it with your config as soon as I get chance.

**Comment by Johmpa** [comment]
I think it may have something to do with the latest version of Home Assistant. I tried downgrading the calendar to the previous version with no avail. Provided I did the downgrade correctly it may be indicative.

**Comment by marksie1988** [comment]
Ok yes I see this bug, It happens when there are less events in the calendar than the `maxEventCount`

I will attempt to get the bugfix released today for this.
