### ISSUE TITLE
"No Events for Today" not showing when maxDaysToShow is set to 1

### ISSUE THREAD

**Issue by vmcosco** [marksie1988/atomic-calendar-revive#339]
### Prerequisites

- [x ] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

I have a card in which I have maxDaysToShow set to "1" and showNoEventsForToday set to "true".  I have no events for today and the card is returning "No events in the next few days".  Alternatively, I have second card with maxDaysToShow set to "7" and for today the card is returning "No Events for Today!"

### Steps to Reproduce

1. set showNoEventsForToday to "true"
2. set maxDaysToShow to "1", observe card text (will only be relevant if no events for today)
3. set maxDaysToShow to "7", observe card text (will only be relevant if no events for today)

**Expected behavior**

The text should be "No Events for Today" even if there is only one day showing in the calendar

**Actual behavior:**

The text shows "No events in the next few days"

**Screenshots**

maxDaysToShow: 1
![image](https://user-images.githubusercontent.com/16504592/97028043-91ddb280-1529-11eb-9587-b3aa1aac171f.png)

maxDaysToShow: 7
![image](https://user-images.githubusercontent.com/16504592/97028136-b46fcb80-1529-11eb-8042-82f3ec4dff68.png)

### Versions

- HomeAssistant Version: 0.116.4
- Plugin Version: 2.5.1

**Comment by marksie1988** [comment]
Thanks for reporting this. I'll take a look at it as soon as I get chance
