### ISSUE TITLE
Not all entities works in Calendar mode

### ISSUE THREAD

**Issue by pabolom92** [marksie1988/atomic-calendar-revive#347]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Describe the bug

Im using Your great calendar, but found some problem. In event mode everything is working fine for me, but when i switch to
calendar mode, one calendar dissapear. Im using my priv calendar, birthday calendar and my wife calendar. All of them are working in event mode, but in calendar mode, my wife calendar is not working.

**Screenshots**

![image](https://user-images.githubusercontent.com/57737162/99410310-9a3fc800-28f2-11eb-83d2-df518877d0b1.png)
![image](https://user-images.githubusercontent.com/57737162/99410391-b80d2d00-28f2-11eb-815c-5c2fcd4ad26d.png)

**Card Configuration**

type: 'custom:atomic-calendar-revive'
entities:
  - entity: calendar.pawelmazella_gmail_com
    color: orange
    icon: 'mdi:face-shimmer'
  - entity: calendar.urodziny
    icon: 'mdi:cake-variant'
  - entity: calendar.inbox
    icon: 'mdi:face-woman-shimmer'
    color: violet
firstDayOfWeek: 1
maxDaysToShow: 7
showDate: true
sortByStartTime: true
showRelativeTime: true
showCurrentEventLine: false
showMonth: false
showWeekDay: true
disableEventLink: true
disabledLocationLink: true
showNoEventsForToday: true
showEventIcon: true
showFullDayProgress: true
showProgressBar: false
noEventsForTodayText: Brak wydarzeń na dziś!
fullDayEventText: Wydarzenie całodzienne
noEventsForNextDaysText: Brak najbliższych wydarzeń!
dateColor: white
timeColor: grey
showLocation: true
disableLocationLink: true

```yaml

```

### Versions

- HomeAssistant Version:
- Plugin Version:

**Comment by marksie1988** [comment]
Hi please can you check the Google calendar settings as listed here: 

https://marksie1988.github.io/atomic-calendar-revive/quickstart#show-more-than-5-events

If not set correctly then items won't show.
