### ISSUE TITLE
select current day by default in calendar mode

### ISSUE THREAD

**Issue by shidlo** [marksie1988/atomic-calendar-revive#354]
In calendar mode, the current day is highlighted but not selected. So today's event will not show up at the bottom of the calendar until the day is selected. 
I suggest adding an option (maybe make it as default) that the current day is auto-selected to show the events when the page is loaded.

**Comment by marksie1988** [comment]
Just an FYI I am looking at this, however I am having some issues getting it to work.

**Comment by shidlo** [comment]
thanks for letting me know. if you need help testing it, feel free to contact me
