### ISSUE TITLE
Don's show "Until *date*" for All Day events

### ISSUE THREAD

**Issue by daaf84** [marksie1988/atomic-calendar-revive#358]
## Summary

Please add the option to hide "Until *date*" for All Day events.
## Motivation

Im my opinion we know when day X ends and day Y starts. So it is not needed for One day All day events.
It can be usefull for multiday all day events.

## Describe alternatives you've considered

I Haven't seen the option in the current list of options.

## Additional context

<img width="348" alt="Schermafbeelding 2020-12-04 om 12 25 47" src="https://user-images.githubusercontent.com/12270887/101158416-f6f9ed00-362b-11eb-87c3-1f47217bb67b.png">

**Comment by marksie1988** [comment]
This is interesting, please could you share your configuration? 

I have tested and on my instance it is showing correctly

**Comment by daaf84** [comment]
`- type: 'custom:atomic-calendar-revive'
    name: Agenda dave
    entities: calendar.werk
    enableModeChange: true
    firstDayOfWeek: 1
    maxDaysToShow: 7
    showDate: true
    showLocation: false
    showRelativeTime: false
    hideFinishedEvents: true
    showMonth: true
    showWeekDay: true
    showFullDayProgress: false
    disableEventLink: true
    showCurrentEventLine: false
    disableCalLocationLink: true
    disableCalEventLink: true
    showLastCalendarWeek: false
    calShowDescription: false
    fullDayEventText: Hele dag
    noEventsForNextDaysText: Geen agendapunten om weer te geven.
    showDescription: true
    showNoEventsForToday: true`

**Comment by marksie1988** [comment]
Ah yes iCal does cause some issues as it logs all day events differently, this does cause some issues with things like this as the card wasn't originally designed for iCal use.

I should be able to do some testing and see if i can resolve this.

**Comment by frettijule** [comment]
Is this fixed? because i have the same issue with the newest version.
![image](https://user-images.githubusercontent.com/10562266/104291586-ff133b00-54bb-11eb-87d1-c3a045855232.png)

my configuration:
- type: custom:atomic-calendar-revive
    name: "Kalender"
    language: de
    dateSize: 120
    eventTitleSize: 110
    untilText: bis
    fullDayEventText: "ganzer Tag"
    showProgressBar: false
    showCurrentEventLine: false
    maxDaysToShow: 14
    dayWrapperLineColor: grey
    titleSize: 110
    showMonth: false
    showWeekDay: true
    showRelativeTime: false
    sortByStartTime: true
    entities:
      - entity: calendar.restmuell
        color: black
      - entity: calendar.papiermuell
        color: blue
      - entity: calendar.plastemuell
        color: yellow
      - entity: calendar.lilamuell
        color: pink

**Comment by marksie1988** [comment]
Hey @frettijule 

Interesting! this was indeed resolved, I will take another look and see what is happening.
