### ISSUE TITLE
"startDaysAhead: -5" Negative value to show past events - Erratic results.

### ISSUE THREAD

**Issue by alnavasa** [marksie1988/atomic-calendar-revive#363]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html>
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html>
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue>

### Steps to Reproduce

1. startDaysAhead: -15
2. Save

**Expected behavior**

Should show previous events en an independent day for each one. (in my case my dad watches sports games after they happen due to time and work). 
. 

**Actual behavior:**

It groups all previous events in one day, In my case this day is today, but I don't know if that is because there is one event past today actually. 
.

**Screenshots**

![Calendar](https://user-images.githubusercontent.com/458370/103305790-57523380-4a0c-11eb-80e4-18cc36f44b0e.jpg)
 

**Card Configuration**

```type: 'custom:atomic-calendar-revive'
name: Deportes
entities:
  - entity: calendar.fwp_real_madrid_fixtures
    eventCalName: Real Madrid - Fútbol
    icon: 'mdi:gas-station'
  - entity: >-
      calendar.https_f1calendar_com_download_f1_calendar_q_gp_ics_t_1609245101261
    eventCalName: Fórmula 1
  - entity: calendar.nfl
    eventCalName: NFL
    icon: 'mdi:gas-station'
  - entity: calendar.real_madrid
    eventCalName: Real Madrid - Baloncesto
maxDaysToShow: 14
maxEventCount: 30
showLocation: false
showMonth: false
showWeekDay: true
showLoader: true
showDate: true
startDaysAhead: -5
showDescription: false
showNoEventsForToday: false
sortByStartTime: true
disableEventLink: true
disableLocationLink: true
refreshInterval: 900
showRelativeTime: true
finishedEventOpacity: 0.9
finishedEventFilter: grayscale(30%)
showProgressBar: true
showeventicon: true
europeanDate: true
enableModeChange: true
untilText: hasta
fullDayEventText: null
noEventsForNextDaysText: null
noEventsForTodayText: null
dateFormat: LL
hoursFormat: 'hh:mm a'



```

### Versions

- HomeAssistant Version: 2020.12.1
- Plugin Version: 2.5.6

**Comment by marksie1988** [comment]
This is not a current feature of the card, I could look and see how complex this would be to add

**Comment by alnavasa** [comment]
> This is not a current feature of the card, I could look and see how complex this would be to add

Thanks!, I thought that the prompt startDaysAhead wasn't meant to be used with negative values, but I had to give it a try.
The request comes from my dad, who watches sports, and watches so many of them after the event has happens, some of them, days after. 

Thanks for your work!

**Comment by alnavasa** [comment]
Working great!, 

Thanks!!

If you want to polish it to the finest detail, I don't know why it only shows relative time in past events if they are only below 24 hours, past that it doesn't show relative timing.
**But that's definitely not an issue for me.**

THAKS!


![Calendar2](https://user-images.githubusercontent.com/458370/103345422-a1c9c380-4a91-11eb-9fe0-aac2bcd43dee.jpg)
