### ISSUE TITLE
Update readme to new style

### ISSUE THREAD

**Issue by marksie1988** [marksie1988/atomic-calendar-revive#372]
Change the readme to make it easier to read and more pleasing

**Comment by funkymonkeymonk** [comment]
Small request for the updated README would be to include an image. When I look at this repo on HACS I can't really get a feel for what adding it offers me visually so it's hard to know if I want it or not.

**Comment by marksie1988** [comment]
@funkymonkeymonk yes I plan on adding this into the new README
