### ISSUE TITLE
Can't get calendar events to display when casting to chromecast

### ISSUE THREAD

**Issue by funkymonkeymonk** [marksie1988/atomic-calendar-revive#377]
## Expected behavior
Calendar events when streamed to Chromecast display the same as when they are on a desktop

## Current behavior
Events display when viewed in web browser but not when streamed to chromecast.

## Possible reasons and solutions
To be honest I have no clue how to debug this. I also see this behavior in the stock calendar widget so I'm not sure the problem is with this widget. I'm asking here because when I asked in the integrations channel in discord I didn't get any response so I'm trying to get help debugging. Happy to pair on this and set up a screen share to show you more about what's going on.

## Steps to reproduce
1. Set up google calendar source as per https://www.home-assistant.io/integrations/calendar.google/
2. Add atomic calendar to a dashboard pulling from the source
3. Cast the dashboard using Home assistant cast. https://www.home-assistant.io/integrations/cast#home-assistant-cast

## Context
This impacts me because I have chromecasts that I use around the house for media consumption and when they go idle I'd like them to show the family dashboard, which includes upcoming events.

**Comment by funkymonkeymonk** [comment]
For more details it says: "The calendar can't be loaded from Home Assistant component"

**Comment by funkymonkeymonk** [comment]
Digging in a bit myself... it seems like the place this is failing is in `getEvents()`  I looked at the stock calendar component and it uses the same method of collecting all of the calendar events via multiple API requests and returning them in a Promise.all. I'm also not seeing that technique used in other components. I'm honestly not sure what to do with this information, but I'm trying to share as much as possible in the event that something helps someone else help me.

**Comment by marksie1988** [comment]
Hey, I will look into this however it sounds more like a limitation of the device being casted to. It potentially doesn't fully support something the function uses

**Comment by funkymonkeymonk** [comment]
Thanks. I did some continued digging and found I can replicate under different circumstances as well. If the dashboard is open and I restart home assistant, when the dashboard is refreshed it will show the same error and require a hard refresh in order to populate. This may be completely different issues but it seems like in the code that if the initial promise fails, it never retries and leaves the board in a bad state until a hard refresh.

**Comment by funkymonkeymonk** [comment]
Also FYI. I got the dashboard to properly display using catt so it looks like this is specific to the way that cast lovelace view works.

**Comment by marksie1988** [comment]
Unfortunately I'm fairly sure I won't be able to resolve this, it looks like from your investigation that it's related to the way the cast works. 

I will close this, but if there is any way around this that people know of I would be happy to implement a potential fix.
