### ISSUE TITLE
Parse url from the event instead of an invalid link

### ISSUE THREAD

**Issue by cociweb** [marksie1988/atomic-calendar-revive#385]
Hello,
Currently the calendar events points to an invalid internal url (<host>/lovelace/undefined) in case of ical(ics) at the title.
As the Ical has the opportunity to include url for each event, please parse the URL property from the calendar (if it has).

## Expected behavior
The event title should point to the url which is provided with the event

## Current behavior
Currently the title link opens an invalid internal url <host>/lovelace/undefined, and the calendar URL property is ignored.

## Screenshot

![kép](https://user-images.githubusercontent.com/1935413/105615983-c0db1d00-5dd3-11eb-8d0f-34579f326142.png)

## Possible solutions
Try to handle a standardized element: https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-5-url-property.html
Here you can find a simple [calendar](https://in-the-sky.org/newscalyear_ical.php?year=2021)

## Checklist

- [ x ] I searched the current issues and the feature is not known.
- [ x ] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
I have looked into this, Unfortunately this is a limitation of the HomeAssistant CalDav integration. 

As you can see [here](https://www.home-assistant.io/integrations/caldav/#sensor-attributes) the sensor attributes don't include the URL property. 

I have requested for this to be added via https://community.home-assistant.io/t/include-caldav-url-property/273150

**Comment by cociweb** [comment]
Thank you for the clarification. in the meantime I've upvoted on ha site for this feature request.

**Comment by marksie1988** [comment]
I have also found that nextcloud only supports up to RFC 5545 so it sounds like there would potentially be a lot of issues with other calendars integrating with this.
