### ISSUE TITLE
Hide "private" events without using blacklist

### ISSUE THREAD

**Issue by coolrazor007** [marksie1988/atomic-calendar-revive#386]
Google Calendar allows me to set some events to "private".  Very few calendars for home automation out there seem to filter these out as an option.  I did find one for MagicMirror2 that did, but I'd much prefer to use HA than MagicMirror2 if possible.  Anyway, blacklist is cool, but this would be nice as well.

For reference (if helpful), this is the module for MagicMirror2 that was able to accomplish this: https://github.com/heskja/MMM-CalendarWeek
It has a user configuration option called: hidePrivate: true

I don't know if this helps (not a programmer), but here is part of the code they used to parse out private events:

`
for (var e in calendar) {
var event = calendar[e];
if(this.config.hidePrivate) {
	if(event.class === "PRIVATE") {
				// do not add the current event, skip it
				continue;
	}
}`

## Expected behavior
An option in configuration to not display "private events"

## Current behavior
Only option to filter out events by keywords

## Possible solutions
Filter out the private events by checking the object attribute for private on the event object

## Context and reason
This allows filtering out private/hidden events using the built in function Google already has.  Otherwise, someone could set an event to private and it'll still show up on the dashboard if no blacklist was setup.  Also, so that you don't have to remember the blacklist keywords you set.

## Checklist

- [X] I searched the current issues and the feature is not known.
- [X] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
I can add this feature sure, However currently will only work with Google Calendar.

**Comment by mattnhanson** [comment]
Is this confirmed to still be working? I have "showPrivate = false" set and noticed that my private Google Calendar events are displaying. v9.4.0

**Comment by marksie1988** [comment]
This probably doesn't work anymore since home assistant changed the API to standardise it and removed a load of features. It's something I want them to add back but so far no joy

**Comment by marksie1988** [comment]
No, I can't do it as home assistant changed their APpI and it no longer shows.
