### ISSUE TITLE
dateSize, timeSize, and eventTitleSize do not appear to have an effect on changing the font sizes

### ISSUE THREAD

**Issue by chadcb** [marksie1988/atomic-calendar-revive#395]
## Expected behaviour
Changing the values of the following should change the font size:
dateSize: 90
timeSize: 90
eventTitleSize: 100

Increasing these values doesn't change the size of the font as expected.

## Current behaviour
Font size stays the same

## Steps to reproduce
Increase values from default and font size stays the same.

## Context
I would like to use the event mode for a wall mounted tablet. But the font size is small and I would like to increase and show only a days worth of events.

## Custom values
dateSize: 150
timeSize: 150
eventTitleSize: 150

## Your environment
HA 2021.1.5

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Just tested and `dateSize: 150` appears to work as expected

![image](https://user-images.githubusercontent.com/159166/106043368-3138b580-60d6-11eb-9bf7-732ca26d1dfe.png)

I will look into the other two as these aren't working as expected. 

However I would recommend using CardMod to make these changes.

**Comment by chadcb** [comment]
Great thanks! I will also look into CardMod. Thanks for the work you put into this calendar!
