### ISSUE TITLE
Automatically increase padding between Event Time and Event Title when using larger font size

### ISSUE THREAD

**Issue by chadcb** [marksie1988/atomic-calendar-revive#398]
Increasing the font size for Event Time and Event Title, the text starts to overlap.

## Expected behaviour
Would like the spacing between time and title to increase as font size increases.

## Current behaviour
With larger fonts, the event time and event tile overlap

## Screenshot
![chrome_iCVKIKurQU](https://user-images.githubusercontent.com/16123033/106051655-574a5f80-60ae-11eb-8983-59b495a79c37.png)

## Possible solutions
Unsure how to resolve.

## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
Hey, I will see if I can amend this to auto grow, however it could be tricky to achieve, I may be able to do some math based off the font size that is set.

**Comment by chadcb** [comment]
Thanks! Would it work better to just have a config options for setting the padding? I was able to edit the JS file manually and add padding as a work around. Trying to setup a dev environment so I can try and help also.

**Comment by marksie1988** [comment]
I'm trying to avoid adding nay options for changes to padding and colours etc. The existing ones were done by the previous developer. 

The issue with adding this is that it makes the already complex config even more complex and is something that can easily be modified with card-mod which is what I would recommend.

**Comment by chadcb** [comment]
No worries. I'm testing out the card-mod card. Also, this calendar is working great! So thanks again for all your effort.

**Comment by marksie1988** [comment]
closing as i feel card mod is the best way to modify the looks of the card without adding too many options to this card.
