### ISSUE TITLE
Open Links in iframe/stay within lovelace

### ISSUE THREAD

**Issue by ezz-91** [marksie1988/atomic-calendar-revive#399]
Possibility of links opening in something like an iframe or staying within lovelace. 
I use a touchscreen tablet in fullscreen mode so when a link is clicked it opens a new tab. 
there's no easy way to go back to the dashboard

**Comment by marksie1988** [comment]
I'm not sure if this is possible with the way home assistant incorporates iframes. But I will look into it.

**Comment by marksie1988** [comment]
I have looked into this and from my research I don't think that this is possible.
