### ISSUE TITLE
Google requiring re-authentication

### ISSUE THREAD

**Issue by IanAdd** [marksie1988/atomic-calendar-revive#401]
## Expected behaviour

Could you prompt the user to delete .google.token when you cannot retrieve any calendar (that you could previously ?)

## Current behaviour

No calendar shown when it showed the day before.

## Possible solutions

Either 
- In the same way that you say when there are no future calendar events available 
- or via persistent notification.

## Context and reason

This happens so infrequently that I forget the simple step required to get it back and working and so have to search until I find how !!

## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by mpejstrup** [comment]
I have now experienced the need for re-authentication 3 times in the last 3 days. Any idea if Google has changed anything?
Love the card BTW :)

**Comment by marksie1988** [comment]
Thanks for this, the Google integration is separate so I'm not sure why the token would keep needing to be deleted, possibly something to ask on the HA community about. 

I will however look at adding a better error to help troubleshooting the issue.
