### ISSUE TITLE
timeColor does not work

### ISSUE THREAD

**Issue by narfotic** [marksie1988/atomic-calendar-revive#403]
## Expected behaviour

If I set timeColor I would expect the color of time (under the event title) in the list view to change to the color I put here.
## Current behaviour

Time stays blue.

## Steps to reproduce

Add 'timeColor: white' to configuration.

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
color on cards I Usually recomendusing Cardmod as this is designed for amending Css. However I will take a Look and see if I can fix this for you./

**Comment by marksie1988** [comment]
I have just run through this and am unable to reproduce the issue you see. when I apply the `timeColor:` and refresh the page, the color is updated as expected. 

Please could you supply your configuration so that I can ensure its not another setting impacting this.

**Comment by nathanmfast** [comment]
I have "timeColor: white" and this is a screenshot of the styling being overridden:
![image](https://user-images.githubusercontent.com/5238018/111420113-a4af7a00-86b8-11eb-9780-c550b355812c.png)

**Comment by nathanmfast** [comment]
Not sure what downstream effects this would have:
![image](https://user-images.githubusercontent.com/5238018/111420303-f8ba5e80-86b8-11eb-923f-1ce6a653de20.png)

**Comment by simonjbamber** [comment]
I have the same issue. Appears that what I'd set for timecolor: (lightgrey) is applied to <tr: class="daywrap"> but this is being overridden by <div class="hoursHTML">.  Hope the attached images help identify the root cause!

![image](https://user-images.githubusercontent.com/74492732/114311104-52118400-9ae5-11eb-9870-f2b4ee0a1db3.png)

**Comment by simonjbamber** [comment]
**Update: Fixed (mostly)**
I found that refreshing the page results in the colour changing to reflect the one I've set in timecolor.  For changes to other configurations on the card the change is visible immediately though (with no refresh needed), so unclear why it would be different for timecolor.

**Comment by marksie1988** [comment]
Hi yes correct a refresh is required, this is because the CSS will need reloading.
