### ISSUE TITLE
Style events with 'RSVP: Maybe' differently

### ISSUE THREAD

**Issue by narfotic** [marksie1988/atomic-calendar-revive#404]
## Expected behaviour

I want to be able to differentiate calendar events with RSVP marked as 'Maybe':

1. I would like to be able to change the icon and text color for such events.
2. I would also like to be able to hide such events.

I use Google calendar and have no idea if this is possible with the information the Google API provides.

## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
1. I think that to implement this would be quite complicated and require quite a lot of thought, unless there was a lot of requests for something like this I would not be able to spend the time required on it. I would need to figure out a way that you could add multiple different icons and colours and then check against a string to make sure it matched etc. 
2. you can hide events with specific titles by using the Blacklist option.
