### ISSUE TITLE
How to close the event list window in Calendar mode.

### ISSUE THREAD

**Issue by charis0728** [marksie1988/atomic-calendar-revive#406]
## Expected behaviour

When I click a day in calendar, the event list window of the day is opened.(current feature)
Then, if I click the day again, the event list window is closed.

## Current behaviour

After the event list window is opened, there is no way to close it.

## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
This is not currently a feature of the card, however I can look at adding this.

**Comment by marksie1988** [comment]
as a workaround to this you can click a date that has no events, this will clear the summary.
