### ISSUE TITLE
Don't show "x events are hidden" or make text customizable

### ISSUE THREAD

**Issue by Bascht74** [marksie1988/atomic-calendar-revive#407]
## Current behaviour
If you set `maxDaysToShow: 35`, only 35 days are shown. There is no information, that the results are filtered.
If you set 'maxEventCount: 3', only 3 events within the 35 days are shown and unter the entries it says "x events are hidden".

## Expected behaviour
I want to get rid of that text or be able zu customize ist (set it to an empty or locallized string). 
Right no, even if the language is "German" (at least for me), it still shows this text in englisch. 

## Screenshot
![image](https://user-images.githubusercontent.com/66269310/107539858-ad96c280-6bc5-11eb-8713-871673def532.png)

## Possible reasons and solutions
Solution: 
- add an option to show/not show this text
- add an option to customize the text, so that you can localize it or set it to ""

## Context and reason
If you use it e.g. for an trash calendar, you don't need that not localized hint :-)

## Checklist

- [X] I searched the current issues and the feature is not known.
- [X] I am mostly sure that the feature will bring more good than bad.

By the way, I want to say right away how great I think the map is and the possibilities to set the appearance and behavior very accurately and precisely. 
Thanks for the great work!

Sebastian

**Comment by marksie1988** [comment]
Hi @Bascht74 ,

The language isn't changing as there   is no language file for German at the moment, I can create one but as I don't speak German would need to use google translate. 

I can add an option to remove this, however it will mean you dont know if events are hidden.

**Comment by Bascht74** [comment]
@marksie1988 
Yes, an option for remove this info would be great!
If you want, I can help with an German language file. For future additions, Deepl.com can be used initially. It usually translates much better than google translate...

**Comment by Bascht74** [comment]
{
	"common": {
		"version": "Version",
		"show_warning": "Warnung anzeigen",
		"error": "Fehler",
		"description": "Erweiterte Kalenderkarte für Home Assistant Lovelace",
		"fullDayEventText": "Ganztägig",
		"untilText": "Bis",
		"noEventsForTodayText": "Keine Einträge für heute.",
		"noEventsForNextDaysText": "Keine Einträge in den nächsten Tagen.",
		"hiddenEventText": "Einige Einträge sind ausgeblendet."
	},
	"ui": {
		"common": {
			"previous": "Zurück",
			"next": "Vor"
		}
	},
	"errors": {
		"invalid_configuration": "Ungültige Konfiguration",
		"update_card": "Der Kalender kann von der Home Assistant-Komponente nicht geladen werden!"
	},
	"required": {
		"name": "Benötigt",
		"secondary": "Folgende Optionen sind notwendig, damit die Lovelace Karte angezeigt werden kann:"
	},
	"main": {
		"name": "Haupteinstellungen",
		"secondary": "Global geltende Optionen",
		"fields": {
			"name": "Name",
			"showColors": "Farben anzeigen",
			"maxDaysToShow": "Maximal angezeigte Tage",
			"showLocation": "Ortssymbol anzeigen",
			"showLoader": "Ladeanimation anzeigen",
			"showDate": "Datum mitanzeigen",
			"showDeclined": "Abgelehnte Einträge anzeigen",
			"sortByStartTime": "Nach Startzeit sortieren",
			"hideFinishedEvents": "Beendete Einträge ausblenden",
			"dateFormat": "Datumsformat",
			"hoursFormat": "Stundenformat",
			"defaultMode": "Standardmodus",
			"linkTarget": "Verknüpfungsziel",
			"refreshInterval": "Aktualisierungsintervall",
			"showRelativeTime": "Relative Zeit anzeigen",
			"firstDayOfWeek": "Erster Wochentag 0-6"
		}
	},
	"event": {
		"name": "Ereignismodus",
		"secondary": "Ereignismodus-spezifische Optionen",
		"fields": {
			"showCurrentEventLine": "Linie vor einem Eintrag anzeigen?",
			"showProgressBar": "Fortschrittsbalken anzeigen?",
			"showMonth": "Monat anzeigen?",
			"showWeekDay": "Wochentag anzeigen?",
			"showDescription": "Beschreibung anzeigen?",
			"disableEventLink": "Links im Ereignistitel deaktivieren?",
			"disableLocationLink": "Links zum Ort deaktivieren?",
			"showNoEventsForToday": "'Keine Einträge heute' anzeigen?",
			"showFullDayProgress": "Ganztägigen Fortschritt der Einträge anzeigen?",
			"untilText": "Text für 'bis':",
			"noEventsForTodayText": "Text für 'Keine Einträge heute':",
			"noEventsForNextDaysText": "Text für 'Keine Einträge in den nächsten Tagen':",
			"fullDayEventText": "Text für 'Ganztägiger Eintrag':",
			"showEventIcon": "Ereignis-Symbol anzeigen?"
		}
	},
	"calendar": {
		"name": "Kalendermodus",
		"secondary": "Kalendermodus-spezifische Optionen",
		"fields": {
			"showLastCalendarWeek": "Letzte Kalenderwoche anzeigen?",
			"disableCalEventLink": "Links für Kalendereinträge deaktivieren?",
			"disableCalLocationLink": "Links für Ortsangaben in Kalendereinträgen deaktivieren?",
			"calShowDescription": "Beschreibung anzeigen?",
			"disableCalLink": "Kalenderlinks deaktivieren?"
		}
	},
	"appearance": {
		"name": "Erscheinungsbild",
		"secondary": "Farbanpassungen usw.",
		"main": {
			"name": "Globale Einstellungen",
			"secondary": "Globale Farbeinstellungen"
		},
		"fields": {
			"locationLinkColor": "Farbe für Links zu Ortsangaben:",
			"dimFinishedEvents": "Erledigte Einträge blasser anzeigen?"
		}
	}
}
