### ISSUE TITLE
Error flooding log :-(

### ISSUE THREAD

**Issue by Repsionu** [marksie1988/atomic-calendar-revive#411]
Log entry popping up frequently (see screensot below)
## Expected behaviour

Do not want to see it as all works OK :-)
## Current behaviour

This is the only reoccuring entry in my logs... 

## Screenshot

![Atomic-revive](https://user-images.githubusercontent.com/46962963/109487566-0e127480-7a8d-11eb-8c39-27255bad1da8.png)

## Steps to reproduce

1. Open HA in browser (any)
2. Click on 'Config'
3. Click on 'Logs'

## Context

It just pops out in logs every time, no more traces of misbehavior otherwise :-)
## Your environment

Raspberry Pi 3+
Latest 2021.3.1 HA core in venv (problem started with latest atomic update and/or beta b5(?)
## Checklist

- [] I searched the current issues and the issue is not known.
- [] I searched the troubleshooting and there's no fix available for this bug.
- [] I searched on Google, YouTube, Reddit and there's no fix.
- [] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Hi, as you havent filled out the form correctly im unable to troubleshoot this issue, please provide information: 

What type of calendar are you using:
copy of the config you are using:
version of hassio:
version of the card installed:

**Comment by Repsionu** [comment]
Updated comments.
Not sure about progress bar but will investigate and let You know.
No changes to calendar config for some months...
Best, JR

**Comment by marksie1988** [comment]
@Repsionu Looking at the error you see, I think that another card is loading the "mwc-linear-progress" bar which is then causing this error to apply. 

I can have a look and see if there is a way for me to check if it is already loaded and not load it if its already there.

**Comment by Repsionu** [comment]
Small update, although of no help :-)
Searched all my HA instance add-ons etc. .js files for mwc-linear-progress but it is not there :-(
Best, JR

**Comment by marksie1988** [comment]
What Lovelace cards do you have installed currently? This may provide more answers.

**Comment by Repsionu** [comment]
Sorry not at PC right now but maybe lovelace resources list- not all in use but ?Repsi P20 Pro-------- Original message --------From: Steven Marks <notifications@github.com>Date: Fri, Mar 5, 2021, 20:53To: marksie1988/atomic-calendar-revive <atomic-calendar-revive@noreply.github.com>Cc: Jüri Rebane <jrebane@hot.ee>, Mention <mention@noreply.github.com>Subject: Re: [marksie1988/atomic-calendar-revive] Error flooding log :-( (#411)
What Lovelace cards do you have installed currently? This may provide more answers.

**Comment by Repsionu** [comment]
My LL resources file (not all in use but here they are).(attatched)Best, JRTäna, 20:53 Steven Marks &lt;notifications@github.com&gt; Kirjutas:
What Lovelace cards do you have installed currently? This may provide more answers.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

{
    "version": 1,
    "key": "lovelace_resources",
    "data": {
        "items": [
            {
                "id": "37a98ce058f34d3fabb191e69a4b325f",
                "type": "module",
                "url": "/hacsfiles/garbage-collection-card/garbage-collection-card.js"
            },
            {
                "id": "3a1eb8cd22064ec8a985cfb4072b4a36",
                "type": "module",
                "url": "/hacsfiles/light-entity-card/light-entity-card.js"
            },
            {
                "id": "e8b5f4efb1384d37a1916b1f5fce425c",
                "type": "module",
                "url": "/hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js"
            },
            {
                "id": "f09489cedcbd4822986bee25f68a54c9",
                "type": "module",
                "url": "/hacsfiles/rgb-light-card/card.js"
            },
            {
                "id": "d5eced2ad3024271b8bbb4153e41456f",
                "type": "module",
                "url": "/hacsfiles/lovelace-card-tools/card-tools.js"
            },
            {
                "id": "724d6ab2479a43b1afa5307734d6b2e0",
                "type": "module",
                "url": "/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js"
            },
            {
                "id": "2178fc5eb3c649fd86be581cc903ffef",
                "type": "module",
                "url": "/hacsfiles/simple-thermostat/simple-thermostat.js"
            },
            {
                "id": "9a4bb8418f354d63b394cefe55c50071",
                "type": "module",
                "url": "/hacsfiles/lovelace-tab-redirect-card/tab-redirect-card.js"
            },
            {
                "id": "d9355c1f967f426f87dd8e04af10bb2e",
                "type": "module",
                "url": "/hacsfiles/sidebar-card/sidebar-card.js"
            },
            {
                "url": "/hacsfiles/scheduler-card/scheduler-card.js",
                "type": "module",
                "id": "9b0fa81d32804cbcb43c917f62e76906"
            },
            {
                "url": "/local/zigzag/zigzag-card.js",
                "type": "module",
                "id": "5b9960e297794df19ab25981b58d09a0"
            },
            {
                "url": "/local/zha-network-visualization-card/zha-network-visualization-card.js",
                "type": "module",
                "id": "e062983247964dcba9df45b404dfaa53"
            },
            {
                "url": "/local/zha-network-card/zha-network-card.js",
                "type": "module",
                "id": "90ee003a9eb54a6d948edfab9a1094f5"
            },
            {
                "url": "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js",
                "type": "module",
                "id": "2c757a293c2f441bb3e655b1a8bc8368"
            },
            {
                "url": "/local/lovelace/resources/custom-ui.js",
                "type": "module",
                "id": "92b7542ee0b8461f89f207c0045e24be"
            },
            {
                "url": "/hacsfiles/lovelace-battery-entity-row/battery-entity-row.js",
                "type": "module",
                "id": "604471b49a36449a84aea493f8a362c8"
            },
            {
                "url": "/hacsfiles/battery-state-card/battery-state-card.js",
                "type": "module",
                "id": "cc92c6bf71ee40afa202117c489f4a53"
            },
            {
                "url": "/local/community/atomic-calendar-revive/atomic-calendar-revive.js",
                "type": "module",
                "id": "6a5b000849bc4e798447c5a0dc77d419"
            },
            {
                "url": "/hacsfiles/flex-table-card/flex-table-card.js",
                "type": "module",
                "id": "dd0ef4df7a794ccdb20f0f5e4e418a04"
            },
            {
                "url": "/hacsfiles/lovelace-auto-entities/auto-entities.js",
                "type": "module",
                "id": "8f4f79273dd84745b5b76accc5795be3"
            },
            {
                "url": "/hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js",
                "type": "module",
                "id": "7dd0a069f4b9411eb4043c0d1d9dbc4d"
            },
            {
                "url": "/local/secondaryinfo-entity-row.js",
                "type": "module",
                "id": "1702e6a401ea49489cdde6582df18da9"
            },
            {
                "url": "/hacsfiles/button-card/button-card.js",
                "type": "module",
                "id": "b409ff16a7a24b7da4e01f1365a9a7a5"
            },
            {
                "url": "/hacsfiles/apexcharts-card/apexcharts-card.js",
                "type": "module",
                "id": "79e4b5d642514b19b767679f594866c3"
            },
            {
                "url": "/local/weather-card-chart.js",
                "type": "module",
                "id": "98e1ea328e9942c9bca3f92b65f42a84"
            },
            {
                "url": "/hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js",
                "type": "module",
                "id": "3dfe9f0cfdfd4e7998b1b942cf1496a0"
            }
        ]
    }
}

**Comment by Repsionu** [comment]
Was so blind like a bat :-(
Problem was a leftover from old time manual install in resources: atomoc-calendar defined twice (see previous post) :-) Deleted the legacy one and... tada
Thanks for Your support, JR
