### ISSUE TITLE
translate "2 events are hidden"

### ISSUE THREAD

**Issue by alnavasa** [marksie1988/atomic-calendar-revive#415]
Possibility to translate "2 events are hidden" either by providing the translation, or get it translated by default with the "language" parameter.

## Expected behaviour
translate "2 events are hidden" 

## Current behaviour
Not translated.

## Screenshot
<img width="490" alt="Captura de pantalla 2021-03-10 a las 9 50 58" src="https://user-images.githubusercontent.com/458370/110602369-3afa1200-8186-11eb-82ec-b10c9f33309d.png">

## Possible solutions
either bu providing the translation of this sentence, or by adding this sentence to the global language option of the card (I personally prefer the second one)

## Context and reason
shows when more events are fetched but the max events number is limited.
## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
Hi There, 
What language are you missing from the card? 

You are now able to customise the text using the property `hiddenEventText:` documented [here](https://marksie1988.github.io/atomic-calendar-revive/options/event-mode-options.html)

Hope this helps

**Comment by alnavasa** [comment]
shouldn't it be working?
v3.4.0

<img width="973" alt="Captura de pantalla 2021-03-16 a las 14 16 39" src="https://user-images.githubusercontent.com/458370/111315172-67200200-8662-11eb-8c43-09eadd8a05e8.png">
