### ISSUE TITLE
Multi-entities not working, multi-day not showing end date

### ISSUE THREAD

**Issue by IanAdd** [marksie1988/atomic-calendar-revive#432]
It used to do what I wanted but somewhere when I wasn't looking these things vanished.

## Expected behaviour

Two calendars should be showing up. Only one does, it's not my calendars either one works but not both.
entities:
  - entity: calendar.name1
  - entity: calendar.name2

Multi-day entry not showing end date any more

## Current behaviour

 Only shows 1st calendar

Multi-day entry should show number of days or end date

## Your environment

v 4.0.0 and previous version.

```
dateColor: black
dateSize: 90
dayWrapperLineColor: black
dimFinishedEvents: true
entities:
  - entity: calendar.airbnb
  - entity: calendar.tripadvisor
eventBarColor: blue
finishedEventFilter: grayscale(100%)
finishedEventOpacity: 0.6
fullDayEventText: Multi-day
locationIconColor: 'rgb(230, 124, 115)'
locationLinkColor: black
locationTextSize: 90
maxDaysToShow: 300
maxEventCount: 3
progressBarColor: blue
showColors: true
showCurrentEventLine: false
showDescription: false
showLocation: false
showMonth: true
showWeekDay: true
showProgressBar: true
showFullDayProgress: true
style: |
  ha-card {
    background: center / cover url("/local/img/cal_faded.jpg");
    background-repeat: repeat-y;
    background-size: 80em;
    --primary-text-color: rgb(250,250,250);
    --paper-listbox-background-color: black;
    text-shadow: 1px 1px 0 #000;
  }
timeColor: blue
timeSize: 90
titleColor: black
titleSize: 100
name: WTS Calendar
type: 'custom:atomic-calendar-revive'
untilText: Until
firstDayOfWeek: 1
```

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Seems like your config is incorrect for the entities, try the below:

```
entities:
  - entity: calendar.airbnb
  - entity: calendar.tripadvisor
```

**Comment by IanAdd** [comment]
> Seems like your config is incorrect for the entities, try the below:
> 
> ```
> entities:
>   - entity: calendar.airbnb
>   - entity: calendar.tripadvisor
> ```

My format is correct in HA, the paste i did into here made it look like that.

**Comment by IanAdd** [comment]
I think I have found the first issue.
If I have two calendars and limit the number of entries to be shown, then this number of entries is selected from the first calendar resulting in none from the 2nd calendar.
Solution would be to select items from both calendars, sort them and then select how many to show.
More explicitly if the number of entries to show is 4, then select 4 from each calendar, sort them and select the first 4 to be displayed.

Still stuck with the end date of multi-day events not showing.
