### ISSUE TITLE
[FEATURE]: Scrollable Calendar 

### ISSUE THREAD

**Issue by bigverm23** [marksie1988/atomic-calendar-revive#434]
## Expected behaviour
User chooses to show events for X number or days, but has the height of the card set statically to X.  Scroll ability would allow user to scroll through X number of days while retaining the card height.

## Current behaviour
Calendar shows events based on defined height of card.

## Context and reason
Maximized space.

## Checklist

- [x] I searched the current issues and the feature is not known.
- [x] I am mostly sure that the feature will bring more good than bad.

**Comment by marksie1988** [comment]
I will see about adding this, for the time being you may be able to use this with card-mod to achieve what you require. 

```
type: 'custom:mod-card'
card_mod:
  style: 'ha-card { height: 737px; overflow-y:scroll!important; }'
```
