### ISSUE TITLE
First day for french is monday, not sunday.

### ISSUE THREAD

**Issue by pinkfloydFR** [marksie1988/atomic-calendar-revive#435]
Hi,

For french user, setting first day of week ( firstDayOfWeek: 0 ) is ok ( if i leave 1 for default, four june is shown as thuesday )

But monday does'nt move in first position.

### **Current behaviour**
![image](https://user-images.githubusercontent.com/49475899/120721995-35833e00-c4cf-11eb-86cb-e778a5c84edf.png)

### **Expected behaviour**

![image](https://user-images.githubusercontent.com/49475899/120722229-b93d2a80-c4cf-11eb-85f0-b14104c79393.png)

Thanks for the great work btw !

edit : 
Strange, in the 'project homepage' your screen capture is showing monday on the left, does i miss a config ?

![image](https://user-images.githubusercontent.com/49475899/120722852-ceff1f80-c4d0-11eb-8b87-ae83d052f401.png)

**Comment by marksie1988** [comment]
Please confirm which version of the card you are using?

This could be a bug with moving to dayjs in the latest version.

**Comment by pinkfloydFR** [comment]
Hi, i confirm i am in 4.0.0 version. i did not notice this problem in 3.x version, so i agreed that it's possibly a new bug in 4.x version.

thank.

**Comment by marksie1988** [comment]
Thanks, I'll do some testing next time I get chance and see what's happening here.

**Comment by marksie1988** [comment]
Just done a quick test and can see the dates are moving correctly but the days don't change along the top, I will sort next time I'm working on the card.

**Comment by marksie1988** [comment]
@pinkfloydFR by default the card will follow the countries default start of week, for example with France it is `LU` for this you do not need to have any setting. However if you would like to have a different day of the week then you can change this with the setting `firstDayOfWeek` and set it from number 0-6 to get the desired day at the start of the week.

0 = Sunday
1 = Monday
2 = Tuesday 
etc.

**Comment by pinkfloydFR** [comment]
In my card i have :         firstDayOfWeek: 0

deleted this line : change nothing
tested with "firstDayOfWeek: 1" : change nothing ( and show wrong date ie 10 june is wednesday )

**Comment by marksie1988** [comment]
It sounds like the old version may be cached in your browser, to check:
1. Press F12 
2. Go to the console tab
3. Check the atomic-calender-revive version shown is correct

If the version is incorrect press `ctrl+shift+r` a few times should force an update. 

Confirm the version is correct then try again 👍

If the version is showing the latest please let me know.

**Comment by pinkfloydFR** [comment]
You're write, console show me version 4.0.0, HACS show me version 4.2.1

I will try to install component mysel manually...

**Comment by pinkfloydFR** [comment]
I don't understand.... 

copied the js file manually, clear all cache, restarting server, console always show me 4.0.0

In the atomic folder i have this now :  
➜  atomic-calendar-revive git:(master) ✗ ll
total 2M
-rw-r--r--    1 root     root        1.9M Jun 10 10:24 atomic-calendar-revive.js
-rw-r--r--    1 root     root       32.7K Jun 10 10:12 atomic-calendar-revive.js.gz
-rw-r--r--    1 root     root      157.1K Jun 10 10:12 atomic-calendar-revive.js.old

old is my backup, 
- why there is a so huge size change ?
- the old file is dated from today, so hacs do the update....

**Comment by marksie1988** [comment]
1.9mb is not right. The card is now only 157kb in size so I'm not sure why it is showing so large there. 

HACS should be installing the correct version, I've just tested it via HACS and it has worked no problem.

**Comment by pinkfloydFR** [comment]
Hum so strange, uninstalled, reinstalled, copied my code, no change, always start with DIM

Recreated an atomic card from scratch, copied my code, it's wprking, first day is LU.

the joys of computing... :D thanks for your support, and this great card !
