### ISSUE TITLE
[CalDAV] The calendar can't be loaded from Home Assistant component

### ISSUE THREAD

**Issue by Firesphere** [marksie1988/atomic-calendar-revive#436]
Not using Google Calendar, but CalDAV Baikal integration. Worked a day before

## Expected behaviour
Calendar should show as yesterday

## Current behaviour
An error message that the calendar could not be loaded from Home Assistant is shown.

## Steps to reproduce
1. Go to a dashboard with a calendar that does not have a Google Calendar

## Context
The calendar not showing is quite a problem, for a calendar card.
The calendar, and the Home Assistant standard card do show events

## Your environment
Raspberry Pi 3B+
Dockerised Home Assistant
Baikal CalDAV server
## System Health

version | core-2021.4.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.10.36-v7+
arch | armv7l
timezone | Pacific/Auckland

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4999
Installed Version | 1.12.4
Stage | running
Available Repositories | 822
Installed Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 7
views | 8
mode | storage

</details>

## Stack trace / logging
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 205, in get
    event_list = await entity.async_get_events(
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 142, in async_get_events
    return await self.data.async_get_events(hass, start_date, end_date)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 175, in async_get_events
    vevent = event.instance.vevent
  File "/usr/local/lib/python3.8/site-packages/vobject/base.py", line 531, in __getattr__
    raise AttributeError(name)
AttributeError: vevent
```

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Could you send the config that you have for the card?

Also if you are able to attach a screenshot. I have tested with both caldav and Google calendar, both worked with my test configurations.

This makes me thing either a configuration issue or some of the configuration is triggering a potential bug.

**Comment by Firesphere** [comment]
I've not changed any configuration since yesterday, so, I'm mildly confused as to what may have caused it. All configs are entirely made via the interface, so no custom things except the entity configurations.

![Screenshot 2021-06-05 at 20-38-38 Overview - Home Assistant](https://user-images.githubusercontent.com/680570/120885855-2f13d400-c63f-11eb-9b64-fc572ed0a4cd.png)


<details><summary>Card configuration</summary>
type: 'custom:atomic-calendar-revive'
entities:
  - entity: calendar.cal1
    icon: 'mdi:account-clock'
    color: green
  - entity: calendar.cal2
    icon: 'mdi:account-clock'
    color: red
  - entity: calendar.cal3
    icon: 'mdi:account-clock'
    color: blue
  - entity: calendar.birthdays
    type: Birthday
    icon: 'mdi:cake'
eventCalName: true
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 7
hideFinishedEvents: true
showRelativeTime: false
showDate: true
sortByStartTime: true
showCurrentEventLine: false
showMonth: true
showWeekDay: false
showProgressBar: true
showFullDayProgress: false
showNoEventsForToday: true
showEventIcon: true
disableLocationLink: false
disableEventLink: true
showHiddenText: false
calShowDescription: false
showLastCalendarWeek: false
disableCalEventLink: true
dimFinishedEvents: true
showDeclined: false
</details>

<details><summary>Calendar config</summary>
- platform: caldav
  username: username@example.com
  password: !secret calendar
  url: https://baikal.domain.com/html/dav.php/calendars/username@example.com/
  calendars:
    - cal1
    - cal2
    - cal3
    - birthdays
</details>

**Comment by marksie1988** [comment]
The config all looks ok although Im not at my PC to test atm. 

If it was working yesterday and nothing has changed, have you attempted a restart of home assistant? 

You didn't upgrade the card at all since it stopped working?

**Comment by Firesphere** [comment]
I've restarted home assistant multiple times, for related and unrelated reasons, but sadly it has not helped.

I am not aware of having upgraded the card at all, or touched the card, since I added it last week. Unless it automatically updates, it is untouched since installation.

**Comment by Firesphere** [comment]
I'm resolving this issue, for the most stupid reason, and a week of my life gone.

I had a typo in the name of one of the calendars, causing HASS to throw an error 400 back... Which the card obviously didn't like.
