### ISSUE TITLE
first day of week is set to sunday, wich is not always the case

### ISSUE THREAD

**Issue by mortalone** [marksie1988/atomic-calendar-revive#444]
hi. i am unable to select wich day of the week is first day. i have tried to select firstDayOfWeek = 1 but it still shows sunday.
i have tried to select another locale in my overall profile. but it still shopws sunday

i have searched everywhere i feel like. but i am unable to resolve the issue.

**Comment by mortalone** [comment]
ok. so on further investigation it seems like it is only the label of the day that is wrong.

**Comment by mortalone** [comment]
so on further investigation. it seems like it is just the day labeling that is wrong

**Comment by marksie1988** [comment]
This will be resolved in the next release.

**Comment by marksie1988** [comment]
The latest version is released, please upgrade and try again, any issues please let me know.

**Comment by marksie1988** [comment]
I am closing this down as there has been no update.

**Comment by Luc3as** [comment]
Hi, I am still having this issue, I am on version 4.5.0 , have configured first day of week 1, and show days 7, labels are still off as 19.7. should me monday.
![image](https://user-images.githubusercontent.com/6381468/126204854-27f93e9b-16a7-4501-936a-8aa3bc87b95c.png)

thanks
