### ISSUE TITLE
12 Hr Display

### ISSUE THREAD

**Issue by maniscalcojohn** [marksie1988/atomic-calendar-revive#446]
Is is possible to display 12Hr time instead of 24Hr time?

**Comment by marksie1988** [comment]
Hey, yes that is possible with the setting 

`hourFormat: 12h`

**Comment by garyak** [comment]
Just this morning I added an afternoon appointment and found the calendar was displaying 24-hour time. I hadn't changed the configuration. HA Core 2021.7.4, AC 4.5.0. I found this question with a search and included the hourFormat: 12h as suggested, but the display remains 24-hour.
![ac](https://user-images.githubusercontent.com/47036329/127893374-5ebc0160-b063-4b0f-aecb-7a0c8caafc3f.jpg)
