### ISSUE TITLE
The calendar can’t be loaded from Home Assistant component.

### ISSUE THREAD

**Issue by davidjmorin** [marksie1988/atomic-calendar-revive#447]
## Expected behaviour

Calendar should display

## Current behaviour

I get nothing showing and tells me to visit link.

## Screenshot
![image](https://user-images.githubusercontent.com/9400895/122627826-1d3f2180-d080-11eb-8c28-b33ff82853ea.png)

## Steps to reproduce

1. Go to 'Edit'
2. Add Atomic Card
3. Manually edit code
4. added config
```
type: custom:atomic-calendar-revive
entities:
  - entity: MYGROUPID@group.calendar.google.com
```
Save

I have re-authed google cal multiple times.  Removed all data and started from scratch.  Nothing works.

**Comment by marksie1988** [comment]
Hey,

You must use the calendar entity id from home assistant. 

It will be something like:

`calendar.MYGROUPID`

**Comment by davidjmorin** [comment]
Thank you!!
