### ISSUE TITLE
Error in the time frame of the event

### ISSUE THREAD

**Issue by imagneti** [marksie1988/atomic-calendar-revive#456]
Hello
I have a problem with the timeframe for the events on the calendar tab.
Instead of the start time, I have a strange entry:
e.g. 2efamult - Work instead of 8:45 AM - work.
You can help
Atomic calendar v4.4.2
ha core 2021.7.2
supervisior 2021.06.8
![calendar1](https://user-images.githubusercontent.com/30090378/125405034-93048780-e3b7-11eb-973d-2672d4eb3144.PNG)
![calendar](https://user-images.githubusercontent.com/30090378/125405037-939d1e00-e3b7-11eb-92a3-0161ce39e44c.PNG)

**Comment by marksie1988** [comment]
Please could you confirm if you have language set and what it is set to?

**Comment by imagneti** [comment]
Polish

**Comment by imagneti** [comment]
screen
![calendar2](https://user-images.githubusercontent.com/30090378/125407373-19ba6400-e3ba-11eb-9336-6948d4b3cc5b.PNG)

**Comment by imagneti** [comment]
fixed time format was - default

**Comment by marksie1988** [comment]
> fixed time format was - default

does this mean you fixed the issue?

**Comment by imagneti** [comment]
yes I hope for what is ok
