### ISSUE TITLE
Calender Card does not Show appointments

### ISSUE THREAD

**Issue by USO0815** [marksie1988/atomic-calendar-revive#461]
Hello together,
Why are some appointments not displayed in the Card view? I have appointments on the 26th and have also saved an icon. However, this is not displayed in the current month although the 26th and other appointments are in this month. If I change the card to the next month, I can see the appointments (the icon) on the corresponding days!
![This month](https://user-images.githubusercontent.com/86083953/126494263-395f34fb-86e9-4ff8-ba35-33dec6d49879.JPG)
![Next month](https://user-images.githubusercontent.com/86083953/126494312-0f4fc118-74be-4a51-8861-4f946c18445c.JPG)

**Comment by marksie1988** [comment]
Have you updated the Google calendar config files? 

You need to specify to tsync 41 days rather than the default 1 week.

**Comment by USO0815** [comment]
Yes, my appointments are also available in Atomic Calendar Revive, but not visible in the current one. if I change the map to august, I also see my appointment from 26.07 see in the pictures!

**Comment by marksie1988** [comment]
Im not sure I understand what is happening. Please could you supply your configuration along with the contents of the file `google_calendars.yaml` most specifically the `max_results` option. 

The appointment on the 26/07, is this a one-off appointment or recurring? 

This will allow me to setup a similar configuration.

Currently it sounds like the max results is set incorrectly in the google_calendars file, if it is set to the default, it will pull the first week or two weeks i believe for the month that is selected.

**Comment by USO0815** [comment]
Ok I have found my mistake! It was just like you said the `max_results` function now everything works exactly as it should, Perfect. Thanks for your support and this great repository! 

Many greetings Nico
