### ISSUE TITLE
Max height with scroll bar

### ISSUE THREAD

**Issue by wbilger** [marksie1988/atomic-calendar-revive#462]
This may be a feature request, but may also be a bug.
On my dashboard I have used this card to show the agenda, but at a fixed height and scroll bar using custom card-mod.
This stop working a few versions ago, not sure which one as I can only roll back to 4.3.0 in hacs. I do have the 
last version that works for me saved, but don't see the version number in it. https://justpaste.it/8pl6m
I used this code to do so;
style: |
    ha-card {
    height: 225px;
    overflow: scroll
}

**Comment by marksie1988** [comment]
This has possibly happened since an option was added to the card to set the height. you will either need to use the card option, or may need to modify your card mod style:

`cardHeight: 225px`

**Comment by wbilger** [comment]
Works perfectly, thanks.

**Comment by mckochan** [comment]
I used to have the following with no scrollbar:
```
style: |
  ha-card {
    height: 245px;
    overflow: hidden;
  }
```

It no longer works either, is there a way to hide the scroll bar with the new option?
