### ISSUE TITLE
12hr Format Display

### ISSUE THREAD

**Issue by garyak** [marksie1988/atomic-calendar-revive#468]
hourFormat: 12h does not correct 24-hour time display.
## Expected behaviour

Seeing events in 24-hour time instead of 12-hour.
## Screenshot

![ac](https://user-images.githubusercontent.com/47036329/128203300-9bafe81e-7a4d-4716-9893-ab59a28fccf2.jpg)

## Your environment

Host Operating System | Home Assistant OS 6.2
-- | --
Update Channel | stable
Supervisor Version | supervisor-2021.06.8
Docker Version | 20.10.6
Disk Total | 457.7 GB
Disk Used | 8.2 GB
Healthy | true
Supported | true
Board | generic-x86-64
Supervisor API | ok
Version API | ok

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Please supply a copy of the configuration for the card? 

Try adding `hoursFormat: 12h` if you dont already have this.

**Comment by garyak** [comment]
Yes. My apologies.
