### ISSUE TITLE
12 vs 24 hr time option

### ISSUE THREAD

**Issue by j6s33m** [marksie1988/atomic-calendar-revive#470]
I used to see my calendar in my preferred 12hr clock format, but I can't seem to figure out how to change it from the latest update that is showing all appointments in military time. Please help

**Comment by marksie1988** [comment]
add the option: 

```
hoursFormat: 12h
```

currently waiting on a module being updated before this will be automatic based on HA settings

**Comment by j6s33m** [comment]
This fixed it. Much appreciated!
