### ISSUE TITLE
Not showing up in HACS?

### ISSUE THREAD

**Issue by Krojack** [marksie1988/atomic-calendar-revive#484]
This won't show up in HACS when I search for it. All I get is the old Atomic Calender and that's all.

![Capture](https://user-images.githubusercontent.com/908461/133481713-8acd1add-95d3-4fe0-8644-ee6a125e9bad.JPG)

I even tried adding as a custom component and then got the error "Repository 'marksie1988/atomic-calendar-revive' exists in the store."

If all else fails I'll manually install but I would rather use HACS for easier updating.

**Comment by marksie1988** [comment]
Hi thanks for logging this, I have checked and the repository is still listed with HACS. 

I am out at the moment but will check tomorrow on my test server to see if it shows for me via HACS.

**Comment by marksie1988** [comment]
@Krojack  I have just tested on the latest HACS version and the repository is showing correctly for me:
![image](https://user-images.githubusercontent.com/159166/133573591-c539760f-2bea-4e4d-a284-d66032ad4732.png)

**Comment by marksie1988** [comment]
Closing as this isn't an issue with the card but most likely local and HACS related.
