### ISSUE TITLE
Add Slovenian language (si)

### ISSUE THREAD

**Issue by AdmiralStipe** [marksie1988/atomic-calendar-revive#496]
Please, add Slovenian language to the interface (code is si). 

I'm not sure, what exactly has to be translated for that, but I can provide necessary translations if you give me a list of strings to be translated (not needed for the whole interface, just the months, days and similar calendar entities...)

**Comment by dolenec** [comment]
If you need I can help regarding translation, just provide English dictionary..

**Comment by AdmiralStipe** [comment]
Great, no work for me then :). 
@marksie1988 , the translation in the JSON file doesn't include day names (Mon, Tue,...) and "in", "ago", "hours", "minutes",... thingies... how do those get translated, especially taking into account not so simple Slovenian grammar with a lot of "specialties", like dual etc (1 minute - 1 minut**a**, 2 minutes - 2 minut**i**, 3 minutes - 4 minut**e**) ?

**Comment by dolenec** [comment]
No problem.. if something will not be translated we can also add later..

**Comment by marksie1988** [comment]
@dolenec please make sure that if you are using the latest card you don't have `hoursFormat` set

That changed with the latest release and could cause this error
