### ISSUE TITLE
[FEATURE] Better UI for agenda in calendar view

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#63]
**Is your feature request related to a problem? Please describe.**
It is hard to read the todays agenda in the calendar view. 
* I know about the switch between calendar/list view and I thought it will be sufficient but it isn't actually. Usually I don't even notice that under current day number is a small icon telling me that somethig is scheduled. I want to see the items for the current day by default under the calendar.
* The way how the items are disaplyed after clicking on the calendar day is unreadable.

**Describe the solution you'd like**
* Show current day agenda by default (click on the date/day not required)
* Show agenda under calendar view in readable way (give a way to customize it)
  e.g. as a bars with calendar-specific background color for all-day events and color dot's for events at specific hours

**Additional context**
I'm proposing the UI to follow same pattern as the one from Google calendar:
![image](https://user-images.githubusercontent.com/8268674/80761146-ecc1be80-8b31-11ea-9bb6-daeb5a27e3ce.png)

**Comment by marksie1988** [comment]
This has been added to v1.3.0, However there were a few things that I still need to develop further such as looking at the full day events and adding the time of the event. 

The array that passes the agenda only passes over the name so I will need to rebuild this to have the date/time in there as well which will take some more time.

**Comment by marksie1988** [comment]
Progress:
- Full events now accessible in calendar mode
- Added option to show time 
- Added option to show location icon 

Plan:
- Order events by date so full day events are shown first
- Add full day event styling 
- Amend styling for normal events 
- Add ability to have bullet point the same colour as the calendar colour 

Problem:
- Blacklist filter throws error on these items so has had to be removed, need to fix
- Title colour throws error, need to add event._config to array.

**Comment by marksie1988** [comment]
Progress:
- Now orders events by date so full day events are shown first
- Added full day event styling 
- Amended styling for normal events 
- Added ability to have bullet point the same colour as the calendar colour 
- Title colour no longer throws error, need to add event._config to array. 

Plan:
- Resolve blacklist filter throwing error on these items so has had to be removed, need to fix

**Comment by marksie1988** [comment]
Example of event styles, along with calendar color for the bullet / style

![image](https://user-images.githubusercontent.com/159166/82150068-c4370580-984f-11ea-8a31-2bd5c6002299.png)
