### ISSUE TITLE
[FEATURE] Custom colors for Sat and Sun

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#64]
**Is your feature request related to a problem? Please describe.**
Most of the calendars have special colors for Sat and Sun which helps to parse the grid more easily.

**Describe the solution you'd like**
Provide configuration for adjusting color of these days

**Comment by marksie1988** [comment]
This has now been added to v1.3.0

**Comment by maxwroc** [comment]
Sorry I wasn't clear enough. I was hoping to have different options for Sat and Sun like:
![image](https://user-images.githubusercontent.com/8268674/81190787-2bcb9600-8fb0-11ea-8303-a3c1f1967028.png)

The colors used here:
Sat: rgba(255, 255, 255, .05)
Sun: rgba(255, 255, 255, .15)

**Comment by marksie1988** [comment]
I have amended this in the latest dev build so will move live on the next merge.

**Comment by mfabiani53** [comment]
How to set colors for sat and sun in the configuration?

**Comment by marksie1988** [comment]
You need to be on v1.3.1 and the settings:
* CalEventSatColor
* CalEventSunColor

[See Documentation](https://marksie1988.github.io/atomic-calendar-revive/options/theme-options.html)
