### ISSUE TITLE
[BUG] Redundant row in calendar view

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#65]
**Describe the bug**
Card in calendar view shows redundant row from the next month.

**To Reproduce**
April 2020

**Expected behavior**
If the row doesn't contain any days from the curren/selected month don't show it

**Screenshots**
![image](https://user-images.githubusercontent.com/8268674/80762506-97d37780-8b34-11ea-8e85-8e59767bcd76.png)

**Setup Information (please complete the following information):**
 - Plugin Version: 1.2.0
 - Chrome

**Comment by marksie1988** [comment]
This can be disabled with the below: 
  `showLastCalendarWeek: false`

However I agree this should be off by default so will swap this in the next release

**Comment by maxwroc** [comment]
ok you're right it worked and I agree this should be like that by default
