### ISSUE TITLE
[FEATURE] Custom color for entity/calendar

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#66]
**Is your feature request related to a problem? Please describe.**
It is hard to distinguish the type/source of the event

**Describe the solution you'd like**
Add an option to set custom calendar color (in entity object)

**Comment by marksie1988** [comment]
@maxwroc there is already an option to have the calendar name displayed under the entity eventCalName.

**Comment by maxwroc** [comment]
Are you talking about calendar or event mode? because I was thinking about calendar mode

**Comment by marksie1988** [comment]
Ah ok yes I'll look into it, currently only the event title is pushed into the array that creates the list, but I will look into something like a different bullet point colour for the different calendar.

**Comment by maxwroc** [comment]
Thanks

**Comment by marksie1988** [comment]
This is to be looked at as part of #63
