### ISSUE TITLE
[FEATURE] Make UI more appealing

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#67]
**Is your feature request related to a problem? Please describe.**
IMO the UI is not very nice (packed/crowdy) and not touch friendly (where most of us use HA on touch devices)

**Describe the solution you'd like**
* add more spacing/paddings
* change ugly day selector which overlaps with content
* add grid lines to make grid easier to parse for eyes
* make entire day container clickable/tapable
* ... (in general make it awesome)

Consider having skins/themes maybe? Like 3-4 appearances which could be chosen via config (they should be very small). This way everyone will adjust easily the card to their taste (as probably no-one likes to configure something with thousands of settings).

**Additional context**
Few simple fixes like grid lines, paddings done in 2 min. IMO looks nicer
![image](https://user-images.githubusercontent.com/8268674/80763689-044f7600-8b37-11ea-9a68-41593360340a.png)
comparing to this
![image](https://user-images.githubusercontent.com/8268674/80764504-bcc9e980-8b38-11ea-9ab0-ce3e2098f684.png)
The problem is that all these numbers and icons are very close to each other and it is hard to extract  fast meaningful information from it

**Comment by marksie1988** [comment]
UI Has now been updated in v1.3.0
