### ISSUE TITLE
[FEATURE] Option "showWeekDay"?

### ISSUE THREAD

**Issue by RonnyAL** [marksie1988/atomic-calendar-revive#70]
Could we have a new option "showWeekDay" in the event view which lets you hide weekdays? Would be pretty useful for my contact calendar (containing birthdays only). I don't really need to know on what weekday friends and family have their birthdays, so I'd love to be able to declutter my UI by removing that information.

**Comment by marksie1988** [comment]
Hi @RonnyAL, 

Im not sure that i understand the request here. do you mean that you want to hide the date from the left of the event information?

**Comment by RonnyAL** [comment]
Thanks for getting back to me, @marksie1988. I mean the weekday. Right now, my card shows (for example):

Jun
28
Sun

I use the card I'm referring to to show upcoming birthdays. And my point is I don't need to know that my friend's birthday is on a Sunday, but it's nice to know that it's on the 28th of June. So I'd like to have just:

Jun
28

Hopefully that makes it clearer what I'm thinking!

**Comment by marksie1988** [comment]
This has now been added to v1.3.0
