### ISSUE TITLE
[BUG] HACS Install asks to write "/community_plugin/atomic_calendar" into resources

### ISSUE THREAD

**Issue by IanAdd** [marksie1988/atomic-calendar-revive#71]
**Describe the bug**
See title
**To Reproduce**
Steps to reproduce the behavior.
Install using HACS
**Expected behavior**

Based on readme.md it should be writing /community_plugin/atomic_calendar_revive

Confused as original version implies it's not being maintained and hence this is the one to use and yet the original version was updated only a few hours ago.

**Screenshots**

**Setup Information (please complete the following information):**
 - Plugin Version
 - Browser & Version [e.g. chrome, safari, chrome mobile etc.]

**Additional context**

**Comment by marksie1988** [comment]
Hi @IanAdd, 

Apologies looks like some parts of the readme haven't been updated properly. 

I will be doing a new release shortly and will resolve this as part of that.

**Comment by IanAdd** [comment]
@marksie1988 thanks. So, should I continue down the path of using the one in your custom repository or have you taken over the original atomic-calendar. I am wanting to use the 'maxEventCount' which appears in the revive documentation but isn't in the original.

**Comment by marksie1988** [comment]
This is the maintained repository, so you should use this one. 

I'm in the process of getting this added to HACS default repos.
