### ISSUE TITLE
[BUG] Custom element not found: atomic-calendar-revive

### ISSUE THREAD

**Issue by ha14937** [marksie1988/atomic-calendar-revive#74]
**Describe the bug**

_Error: Custom element not found: atomic-calendar-revive_

**To Reproduce**
Steps to reproduce the behavior.

1. Installed via HACs, per instructions [here](https://github.com/marksie1988/atomic-calendar-revive#hacs-recommended)
2. Confirmed the URL got placed in the Lovelace Resources tab
3. Confirmed the files got placed in the www/community/ directory
4. Added manual card with the [Simple Configuration](https://github.com/marksie1988/atomic-calendar-revive#simple-configuration), except with my calendar.XXXX 
5. Restarted HA, no change to error

**Expected behavior**
just trying to get the card to display at this point.

**Screenshots**
URL was properly placed in the Lovelace Resources tab:
![image](https://user-images.githubusercontent.com/56581105/80965733-12c0ba80-8de1-11ea-8b30-9015a8a9df91.png)

Files stored (by HACs) in the www/community/ directory:
![image](https://user-images.githubusercontent.com/56581105/80964235-7d242b80-8dde-11ea-9529-4acd178f86b2.png)

Initial card config:
![image](https://user-images.githubusercontent.com/56581105/80965589-c70e1100-8de0-11ea-9011-1fd286c96320.png)

**Setup Information (please complete the following information):**
 - Plugin Version: v1.2.0 
 - Browser & Version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**Additional context**
Sorry, may not be an actual bug - but I have checked all the things I know to check (directories for the files, resources page, etc and it all looks correct -  so not sure where else to turn!

**Comment by marksie1988** [comment]
@ha14937  there is currently an issue with the readme that will be fixed in the next release 

The directory you should put the file in should be /community/atomic-calendar-revive. 

This should resolve the issue you are seeing.

**Comment by ha14937** [comment]
@marksie1988 that did it, thanks a lot!
