### ISSUE TITLE
[BUG] Day selector doesn't work

### ISSUE THREAD

**Issue by maxwroc** [marksie1988/atomic-calendar-revive#82]
**Describe the bug**
Day selector stays on the current day after clicking on the other one. The problem is that the agenda is shown correctly for the clicked day so it is confusing now. And it is regression comparing to prev version.

**To Reproduce**
Click on the other day in calendar view

**Expected behavior**
"current day" selection should switch to clicked/chosen day

**Setup Information (please complete the following information):**
 - v1.3.0

**Comment by marksie1988** [comment]
Hi @maxwroc ive just tested this with an older version 1.2.0 but this still doesnt change the selected day. 

However i agree that it should, even if its a different color to make it show as the selected day. I will take a look at this.

**Comment by marksie1988** [comment]
Added this to the latest release.
