### ISSUE TITLE
[BUG] Setting "Show Loader" is broken (always true)

### ISSUE THREAD

**Issue by RonnyAL** [marksie1988/atomic-calendar-revive#84]
Discovered this when trying to turn off the loader for a calendar card I have. Looking at the code editor, I see `showLoader: false`, but after saving the loader still shows. When I open the visual editor again the `Show Loader` setting is set to true again - despite still showing as false in the code editor.

I'm using v1.3.0 and running Chrome 81.0.4044.129 on Windows 10.

**Comment by marksie1988** [comment]
I have just tested and this works without any issues. 

Could you show a screenshot of the issue? along with a copy of the config for the card?

**Comment by RonnyAL** [comment]
I made a gif showing the behaviour I'm seeing:

![Video demonstration](https://i.imgur.com/8yN94k3.gif)

Looks like the embedded gif may not be working. If not, [here's a link](https://gfycat.com/vibrantdetailedindianglassfish).

I tried clearing my cache, and I also tried Firefox 72.0.2 (x64) with the same results. The card configuration is:

```
type: 'custom:atomic-calendar-revive'
entities:
  - calendar.my_email_address
name: Testing
showLoader: false
```

**Comment by marksie1988** [comment]
Ok I see now. 

The showLoader is for when the plugin loads into Lovelace. 

What you are looking at in the gif is the event progress bar. Please try:
```
showProgressBar: false
```

[docs](https://marksie1988.github.io/atomic-calendar-revive/options/event-options.html)

**Comment by RonnyAL** [comment]
Oops. I'm not sure how I figured "loader" referred to the progress bar. I'm not able to test your fix right now but it'll probably work!

Having that said, is it not weird still that the toggle keeps reverting to true despite being set to false in code editor?

**Comment by marksie1988** [comment]
Yes, the code editor is still in an alpha state, it needs quite a bit more work :)
