### ISSUE TITLE
[FEATURE] Remove time and reduce div height

### ISSUE THREAD

**Issue by musicaways** [marksie1988/atomic-calendar-revive#99]
Hi,
is it possible to remove the time from the reminders and reduce the height of the div to have a more compact interface?

like in the image shown?

![Cattura](https://user-images.githubusercontent.com/18104463/81745744-9f384080-94a5-11ea-8e96-83dba22ad377.JPG)

**Comment by marksie1988** [comment]
Hi @musicaways, 

I cant get the same result as you on my test instance of HA. would it be possible to post a copy of the card configuration? 

If i remove the time then the next event is close to the previous event.

![image](https://user-images.githubusercontent.com/159166/81819259-faf6de00-9526-11ea-9f31-073054a33821.png)

**Comment by musicaways** [comment]
@marksie1988 In my case it would be perfect as shown in your example. Because I use a 3.5-inch 480x320px monitor and the space it's important :)
How can I get this result?

This is my current configuration:

  - title: Menu' Settimanale
    path: menu
    panel: true
    cards:
     - type: "custom:atomic-calendar-revive"
       name: ""
       enableModeChange: true
       defaultMode: 1
       timeSize: 0
       maxDaysToShow: 7
       showLocation: false
       showDate: false
      #  showTime: false
       showLoader: false
       showMonth: false
       disableLocationLink: true
       disableEventLink: true
       entities:
         - entity: calendar.menu

**Comment by marksie1988** [comment]
I think you need to add the below. This will remove the div that is used for the hours. Rather than making the timeSize 0

```yaml
showHours: false
```

**Comment by musicaways** [comment]
Now is perfect!!

thank you @marksie1988
